import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const SVG_DIR = join(DIR, "svgs");
const PROMPT_DIR = join(DIR, "prompts");
const W = 1600;
const H = 900;

const C = {
  bg: "#F5F0E6", paper: "#FFFCF4", ink: "#171717", muted: "#5E6670",
  line: "#D8D0C0", teal: "#2F7373", maroon: "#722F37", brown: "#8B7355",
  cobalt: "#2563EB", red: "#B42318", green: "#16803C", amber: "#B7791F",
  blueBg: "#F3F7FF", tealBg: "#F2FBF8", redBg: "#FFF5F3", amberBg: "#FFF9E8",
};

type Slide = {
  file: string; stage: string; title: string[]; subtitle: string; labels: string[];
  evidence: string; objective: string; notes: string; visual: string; kind: string;
};

const slides: Slide[] = [
  { file: "01-slide-cover", stage: "feedback-guided search", title: ["Search Needs More Than", "More Samples"], subtitle: "Stanford CS329A Part 7 - diversity, feedback, selection, and stopping", labels: ["Diversity", "Feedback", "Selection", "Stop"], evidence: "00:00-01:11 / synthesis", objective: "Frame search as a controlled system rather than raw sampling.", notes: "More candidates create opportunities, not a correctness guarantee. Code execution and document evidence are different feedback channels. Ask learners to identify the budget and stop condition.", visual: "Candidate branches pass through distinct execution and evidence feedback paths into a bounded selector.", kind: "cover" },
  { file: "02-slide-contest-problem", stage: "task structure", title: ["Contest Code Requires a Whole", "Problem-Solving Chain"], subtitle: "The model must interpret, plan, implement, and survive hidden tests.", labels: ["Statement", "Algorithm", "Code", "Hidden tests"], evidence: "01:11-04:30 + AlphaCode", objective: "Contrast contest problem solving with short autocomplete.", notes: "Competitive programming is structured and mechanically scored, but it still requires a longer chain than function completion. It is not the same as all professional software work.", visual: "Four-stage pipeline with an explicit failure gate after each stage.", kind: "pipeline" },
  { file: "03-slide-alphacode-pipeline", stage: "candidate search", title: ["AlphaCode Searches a", "Million-Scale Candidate Space"], subtitle: "Sampling creates coverage; execution and clustering compress the pool.", labels: ["Up to 1M", "Public checks", "Behavior clusters", "10 submissions"], evidence: "04:30-09:40 + arXiv:2203.07814v1", objective: "Explain AlphaCode's generate-filter-cluster-select pipeline.", notes: "The million-scale figure describes the reported system, not a recommended budget. Public examples reject some failures but cannot prove hidden-test correctness.", visual: "A large candidate fan narrows through execution filtering and behavioral clusters.", kind: "fan" },
  { file: "04-slide-coverage-selection", stage: "metric boundary", title: ["Finding One Correct Program", "Is Not the Same as Selecting Ten"], subtitle: "pass@k measures candidate coverage; 10@k also measures small-set selection.", labels: ["Correct exists", "Pool size k", "Select 10", "Submit"], evidence: "09:40-16:35 + AlphaCode", objective: "Separate coverage from useful selection.", notes: "A correct candidate can exist and never reach the submission tray. Formal metric definitions belong to the paper; the visual teaches the systems distinction.", visual: "A candidate pool with one correct program beside a ten-slot selected tray that can miss it.", kind: "compare" },
  { file: "05-slide-diversity-saturation", stage: "scaling limit", title: ["Compute Keeps Rising After Useful", "Diversity Starts Flattening"], subtitle: "Redundant candidates and weak ranking turn more samples into diminishing return.", labels: ["Compute", "Useful diversity", "Redundancy", "Selector load"], evidence: "16:35-24:38 + AlphaCode", objective: "Show why sample count is not equivalent to independent opportunity.", notes: "This is a sourced interpretation of the lecture and AlphaCode ablations, not a universal law. The curve is schematic and intentionally has no empirical axis values.", visual: "Rising compute bars next to a saturating diversity curve and growing selector queue.", kind: "curve" },
  { file: "06-slide-alphacode2-system", stage: "system redesign", title: ["AlphaCode 2 Improves the Candidate", "Supply and the Ranker"], subtitle: "A policy family feeds execution, clustering, and a learned scoring model.", labels: ["Policy A", "Policy B", "Policy C", "Scorer"], evidence: "24:38-30:20 + AC2 report", objective: "Show how generator diversity and ranking are co-designed.", notes: "The family of fine-tuned policies targets diversity. Filtering, clustering, and scoring are competitive-programming-specific components.", visual: "Three policy streams converge through filter, cluster, and score stages.", kind: "family" },
  { file: "07-slide-results-denominator", stage: "claim calibration", title: ["The Headline Result", "Needs Its Denominator"], subtitle: "Strong reported performance remains contest-, task-, and budget-specific.", labels: ["43% solved", "25% prior", "85th percentile", "77 problems"], evidence: "30:20-38:20 + AC2 report pp.1-3", objective: "Attach AlphaCode 2's result to its evaluation frame.", notes: "The technical report text states 85th percentile; a lecture visual appears near 87. Use the primary report. Up to one million candidates were sampled per problem.", visual: "Three metric cards anchored to a denominator strip with tasks, submissions, and candidate budget.", kind: "metrics" },
  { file: "08-slide-adaptive-search", stage: "allocation", title: ["Harder Problems Need Adaptive Search,", "Not Just a Wider Fan"], subtitle: "Route by difficulty toward sampling, decomposition, tree search, or human review.", labels: ["Easy", "Medium", "Hard", "Unfamiliar"], evidence: "39:25-46:33 / discussion", objective: "Generalize beyond flat sampling while preserving evidence labels.", notes: "These are lecture discussion directions, not AlphaCode 2 evaluated components. The router is a teaching design.", visual: "Difficulty bands route into four distinct search strategies.", kind: "router" },
  { file: "09-slide-knowledge-gap", stage: "reasoning failure", title: ["One Missing Fact Can Corrupt", "the Rest of a Reasoning Chain"], subtitle: "Fluent continuation can hide the point where uncertainty became a guess.", labels: ["Known", "Knowledge gap", "Guess", "Wrong answer"], evidence: "46:33-50:40 + Search-o1", objective: "Locate the failure at the unsupported transition.", notes: "The lecture uses a chemistry example. This original diagram abstracts the pattern and does not reproduce the course frame.", visual: "A reasoning chain breaks at a red knowledge-gap node, then continues with inherited error.", kind: "chain" },
  { file: "10-slide-agentic-retrieval", stage: "search action", title: ["Agentic Retrieval Searches When", "the Reasoning Process Needs It"], subtitle: "Search becomes a recurrent action instead of a one-time preface.", labels: ["Reason", "Detect gap", "Search", "Resume"], evidence: "50:40-55:50 + arXiv:2501.05366", objective: "Contrast static retrieval with recurrent retrieval control.", notes: "Agentic here means the model can trigger a controlled search action. It does not imply unrestricted autonomy.", visual: "A four-stage reasoning loop triggers search and returns evidence to the current state.", kind: "loop" },
  { file: "11-slide-reason-documents", stage: "context control", title: ["Search-o1 Compresses Documents", "Into Focused Evidence"], subtitle: "Retrieve sources, reason within them, extract evidence, then resume the main chain.", labels: ["Documents", "Reason in docs", "Evidence", "Main context"], evidence: "55:50-68:15 + arXiv:2501.05366", objective: "Explain Reason-in-Documents and its boundary.", notes: "Focused extraction can reduce context noise. It cannot guarantee that sources are correct, complete, or representative.", visual: "Three documents enter an evidence extractor before a compact evidence packet rejoins reasoning.", kind: "docs" },
  { file: "12-slide-search-diagnostic", stage: "teaching diagnostic", title: ["Audit the Loop Before", "Trusting the Answer"], subtitle: "Five questions expose where a search-enhanced agent can fail.", labels: ["Diversity", "Feedback", "Selection", "Failure", "Stopping"], evidence: "whole lecture / synthesis", objective: "Apply a reusable bounded-search diagnostic.", notes: "Ask what creates diversity, what feedback is observed, how selection works, what happens when feedback is wrong, and when the system stops.", visual: "Five diagnostic cards surround a bounded search loop with an uncertainty stop.", kind: "diagnostic" },
];

function ensure(path: string) { if (!existsSync(path)) mkdirSync(path, { recursive: true }); }
function esc(s: string) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function measure(s: string) { return [...s].reduce((n, ch) => n + (/[^\x00-\x7F]/.test(ch) ? 1.7 : 1), 0); }
function wrap(s: string, max: number) { const out: string[] = []; let line = ""; for (const word of s.split(/\s+/)) { const next = line ? `${line} ${word}` : word; if (measure(next) > max && line) { out.push(line); line = word; } else line = next; } if (line) out.push(line); return out; }
function txt(x: number, y: number, lines: string[], size: number, color = C.ink, weight = 700, lh = Math.round(size * 1.18), anchor: "start" | "middle" = "start", mono = false) { return lines.map((line, i) => `<text class="${mono ? "mono" : "ui"}" x="${x}" y="${y + i * lh}" fill="${color}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}">${esc(line)}</text>`).join(""); }
function card(x: number, y: number, w: number, h: number, stroke = C.line, fill = C.paper, rx = 8) { return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`; }
function arrow(x1: number, y1: number, x2: number, y2: number, color = C.teal, width = 4, dash = "") { return `<path d="M${x1} ${y1} L${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ""} marker-end="url(#arrow)"/>`; }
function pill(x: number, y: number, w: number, label: string, color = C.teal, fill = C.paper) { return `${card(x, y, w, 56, color, fill)}${txt(x + w / 2, y + 35, [label], 18, color, 850, 22, "middle", true)}`; }
function shell(inner: string) { return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><pattern id="grid" width="46" height="46" patternUnits="userSpaceOnUse"><path d="M46 0 L0 0 0 46" fill="none" stroke="${C.line}" stroke-width="1" opacity="0.38"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="context-stroke"/></marker></defs><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Inter","Segoe UI",Arial,sans-serif;letter-spacing:0}.mono{font-family:"SFMono-Regular","SF Mono",Consolas,monospace;letter-spacing:0}</style><rect width="${W}" height="${H}" fill="${C.bg}"/><rect width="${W}" height="${H}" fill="url(#grid)"/><rect x="42" y="42" width="1516" height="816" rx="8" fill="${C.paper}" opacity="0.92"/>${inner}</svg>`; }
function badge(s: Slide) { const w = Math.max(220, measure(s.stage) * 12 + 54); return `${card(84, 68, w, 43, C.teal, C.tealBg)}${txt(108, 97, [s.stage.toUpperCase()], 17, C.teal, 900, 21, "start", true)}`; }
function evidence(s: Slide) { const label = `PART 7  ${s.evidence}`; const w = Math.min(650, Math.max(330, measure(label) * 9.4 + 42)); return `${card(1516 - w, 68, w, 43, C.line, C.paper)}${txt(1516 - w / 2, 97, [label], 15, C.muted, 760, 19, "middle", true)}`; }
function header(s: Slide) { return `${badge(s)}${evidence(s)}${txt(86, 188, s.title, 50, C.ink, 920, 57)}${txt(90, 188 + s.title.length * 57 + 18, wrap(s.subtitle, 91), 23, C.muted, 560, 29)}`; }
function caveat(x: number, y: number, w: number, label: string) { const lines = wrap(label, Math.floor(w / 12)); return `${card(x, y, w, 40 + lines.length * 25, C.red, C.redBg)}${txt(x + 18, y + 27, ["BOUNDARY"], 14, C.red, 900, 18, "start", true)}${txt(x + 18, y + 54, lines, 18, C.ink, 630, 25)}`; }

function renderCover(s: Slide) { const ys = [325, 420, 515, 610]; const fan = ys.map((y, i) => `${arrow(900, 475, 1010, y, C.cobalt, 3)}${pill(1010, y - 28, 165, ["candidate", "program", "query", "source"][i], C.cobalt, C.blueBg)}`).join(""); return shell(`${badge(s)}${evidence(s)}${txt(90, 245, s.title, 64, C.ink, 930, 74)}${txt(94, 455, wrap(s.subtitle, 38), 25, C.muted, 560, 32)}${pill(100, 650, 145, "Diversity", C.cobalt, C.blueBg)}${pill(260, 650, 145, "Budget", C.brown, C.amberBg)}${card(690, 405, 210, 140, C.cobalt, C.blueBg)}${txt(795, 465, ["GENERATOR"], 21, C.cobalt, 900, 25, "middle", true)}${txt(795, 505, ["fixed model"], 17, C.ink, 700, 21, "middle")}${fan}${arrow(1175, 372, 1250, 405, C.green)}${arrow(1175, 562, 1250, 540, C.teal)}${pill(1250, 377, 155, "execute", C.green, C.tealBg)}${pill(1250, 512, 155, "evidence", C.teal, C.tealBg)}${arrow(1405, 405, 1440, 475, C.maroon)}${arrow(1405, 540, 1440, 475, C.maroon)}${card(1440, 410, 75, 130, C.maroon, C.redBg)}${txt(1477, 461, ["SELECT"], 13, C.maroon, 900, 16, "middle", true)}${txt(1477, 501, ["stop"], 14, C.ink, 700, 18, "middle")}`); }
function renderPipeline(s: Slide) { const items = [[90,"STATEMENT","interpret",C.cobalt],[450,"ALGORITHM","choose",C.brown],[810,"CODE","implement",C.teal],[1170,"HIDDEN TESTS","survive",C.maroon]] as const; const body = items.map(([x,a,b,color],i)=>`${card(x,430,300,230,color,C.paper)}${txt(x+150,490,[a],20,color,900,24,"middle",true)}${txt(x+150,550,[b],26,C.ink,780,31,"middle")}${pill(x+60,590,180,i<3?"failure gate":"judge",color,i<3?C.redBg:C.tealBg)}${i<3?arrow(x+300,545,x+350,545,C.teal):""}`).join(""); return shell(`${header(s)}${body}${caveat(310,750,980,"Competitive programming is structured and executable; it is not a complete proxy for professional software engineering.")}`); }
function renderFan(s: Slide) { const ys=[390,455,520,585,650]; const fan=ys.map((y,i)=>`${arrow(340,520,560,y,C.cobalt,3)}${pill(560,y-27,170,`sample ${i+1}`,C.cobalt,C.paper)}`).join(""); return shell(`${header(s)}${card(90,450,250,140,C.cobalt,C.blueBg)}${txt(215,505,["POLICY"],21,C.cobalt,900,25,"middle",true)}${txt(215,548,["up to 1M"],18,C.ink,720,22,"middle",true)}${fan}${arrow(730,520,895,520,C.green)}${pill(895,492,170,"public checks",C.green,C.tealBg)}${arrow(1065,520,1175,520,C.teal)}${pill(1175,492,160,"clusters",C.teal,C.tealBg)}${arrow(1335,520,1420,520,C.maroon)}${pill(1420,492,100,"10",C.maroon,C.redBg)}${caveat(335,750,930,"Public checks can reject failures; passing them does not prove correctness on hidden tests.")}`); }
function renderCompare(s: Slide) { const pool=Array.from({length:28},(_,i)=>{const x=150+(i%7)*62,y=465+Math.floor(i/7)*62,ok=i===9;return `<circle cx="${x}" cy="${y}" r="20" fill="${ok?C.green:C.line}"/>${ok?txt(x,y+5,["OK"],11,"#fff",900,14,"middle",true):""}`}).join(""); const tray=Array.from({length:10},(_,i)=>`${card(915+(i%5)*100,465+Math.floor(i/5)*100,78,72,i===7?C.red:C.maroon,i===7?C.redBg:C.paper)}${txt(954+(i%5)*100,508+Math.floor(i/5)*100,[String(i+1)],16,i===7?C.red:C.maroon,850,20,"middle",true)}`).join(""); return shell(`${header(s)}${card(80,405,560,320,C.cobalt,C.blueBg)}${txt(120,450,["PASS@K  /  CORRECT EXISTS"],18,C.cobalt,900,22,"start",true)}${pool}${card(760,405,760,320,C.maroon,C.paper)}${txt(800,450,["10@K  /  SELECT A SMALL SET"],18,C.maroon,900,22,"start",true)}${tray}${txt(1280,690,["correct candidate can be missed"],18,C.red,800,22,"middle")}${caveat(340,765,920,"Candidate coverage and returned reliability belong to different parts of the system.")}`); }
function renderCurve(s: Slide) { const bars=[80,145,220,300,390,500].map((h,i)=>`<rect x="110" y="${710-h}" width="80" height="${h}" rx="5" fill="${C.brown}" opacity="${0.58+i*0.07}" transform="translate(${i*100} 0)"/>`).join(""); const curve=`<path d="M830 675 C900 510 980 455 1080 430 C1180 405 1300 400 1490 398" fill="none" stroke="${C.teal}" stroke-width="7"/><path d="M830 700 L1490 380" fill="none" stroke="${C.line}" stroke-width="3" stroke-dasharray="10 8"/>`; return shell(`${header(s)}${card(80,400,660,340,C.brown,C.amberBg)}${txt(120,445,["SAMPLING COMPUTE"],18,C.brown,900,22,"start",true)}${bars}${txt(410,720,["keeps rising"],18,C.brown,800,22,"middle")}${card(790,400,730,340,C.teal,C.tealBg)}${txt(830,445,["USEFUL DIVERSITY"],18,C.teal,900,22,"start",true)}${curve}${txt(1180,600,["schematic saturation"],19,C.teal,800,23,"middle")}${caveat(340,770,920,"Schematic interpretation only: no empirical axis values or universal scaling law are claimed.")}`); }
function renderFamily(s: Slide) { const policies=[420,520,620].map((y,i)=>`${pill(90,y,210,`policy ${String.fromCharCode(65+i)}`,C.cobalt,C.blueBg)}${arrow(300,y+28,500,535,C.cobalt,3)}`).join(""); const stages=[[500,"EXECUTE",C.green],[760,"CLUSTER",C.teal],[1020,"SCORE",C.brown],[1280,"SUBMIT",C.maroon]] as const; return shell(`${header(s)}${policies}${stages.map(([x,label,color],i)=>`${card(x,465,210,140,color,C.paper)}${txt(x+105,520,[label],19,color,900,23,"middle",true)}${txt(x+105,563,[["public tests"],["behavior"],["learned rank"],["max 10"]][i],17,C.ink,700,21,"middle")}${i<3?arrow(x+210,535,x+250,535,C.teal):""}`).join("")}${caveat(310,750,980,"Every component exploits competitive programming's unusually strong executable feedback.")}`); }
function renderMetrics(s: Slide) { const cards=[[90,"43%","AlphaCode 2 solved",C.teal],[560,"25%","AlphaCode solved",C.maroon],[1030,"85th","estimated percentile",C.cobalt]] as const; return shell(`${header(s)}${cards.map(([x,n,label,color])=>`${card(x,405,420,220,color,C.paper)}${txt(x+210,490,[n],56,color,930,66,"middle",true)}${txt(x+210,565,[label],20,C.ink,730,24,"middle")}`).join("")}${card(90,675,1360,90,C.brown,C.amberBg)}${txt(770,712,["77 SELECTED PROBLEMS  |  UP TO 1M CANDIDATES EACH  |  MAX 10 SUBMISSIONS"],19,C.brown,900,23,"middle",true)}${txt(770,747,["Primary report text controls: 85th percentile (not the lecture graphic's apparent ~87%)."],17,C.red,740,21,"middle")}`); }
function renderRouter(s: Slide) { const rows=[[415,"EASY","flat sampling",C.green],[505,"MEDIUM","decompose",C.cobalt],[595,"HARD","tree / backtrack",C.maroon],[685,"UNFAMILIAR","human review",C.brown]] as const; return shell(`${header(s)}${card(90,455,250,190,C.brown,C.amberBg)}${txt(215,515,["DIFFICULTY"],20,C.brown,900,24,"middle",true)}${txt(215,558,["ROUTER"],28,C.ink,900,33,"middle",true)}${txt(215,610,["budget-aware"],17,C.muted,700,21,"middle")}${rows.map(([y,a,b,color])=>`${arrow(340,550,610,y+28,color,3)}${pill(610,y,200,a,color,C.paper)}${arrow(810,y+28,970,y+28,color,3)}${pill(970,y,390,b,color,C.paper)}`).join("")}${caveat(360,790,880,"Lecture discussion directions, not reported AlphaCode 2 components or ablation results.")}`); }
function renderChain(s: Slide) { const xs=[100,390,680,970,1260]; const labs=["known fact","reasoning","KNOWLEDGE GAP","unsupported guess","wrong answer"]; const colors=[C.teal,C.teal,C.red,C.maroon,C.red]; return shell(`${header(s)}${xs.map((x,i)=>`${card(x,470,230,150,colors[i],i===2?C.redBg:C.paper)}${txt(x+115,525,wrap(labs[i],18),20,colors[i],900,26,"middle",true)}${i<4?arrow(x+230,545,x+275,545,i===2?C.red:C.teal,4,i===2?"9 7":""):""}`).join("")}${txt(800,700,["Fluency continues after evidence stops."],28,C.red,850,34,"middle")}${caveat(380,765,840,"The failure begins at the unsupported transition, not only at the final answer.")}`); }
function renderLoop(s: Slide) { const nodes=[[260,520,"REASON",C.cobalt],[600,405,"DETECT GAP",C.red],[970,405,"SEARCH",C.teal],[1250,520,"RESUME",C.green]] as const; return shell(`${header(s)}${nodes.map(([x,y,label,color])=>`${card(x-120,y-65,240,130,color,C.paper)}${txt(x,y-10,[label],19,color,900,23,"middle",true)}${txt(x,y+30,[label==="SEARCH"?"controlled action":label==="DETECT GAP"?"uncertainty":"state update"],16,C.ink,680,20,"middle")}`).join("")}${arrow(380,520,480,445,C.cobalt)}${arrow(720,405,850,405,C.red)}${arrow(1090,445,1130,500,C.teal)}<path d="M1250 585 C1120 745 470 745 260 585" fill="none" stroke="${C.green}" stroke-width="4" marker-end="url(#arrow)"/>${caveat(390,760,820,"Agentic retrieval controls when to search; it does not certify the returned sources.")}`); }
function renderDocs(s: Slide) { const docs=[430,520,610].map((y,i)=>`${card(90,y,210,70,C.cobalt,C.blueBg)}${txt(195,y+42,[`document ${i+1}`],17,C.cobalt,800,21,"middle",true)}${arrow(300,y+35,570,540,C.cobalt,3)}`).join(""); return shell(`${header(s)}${docs}${card(570,450,320,190,C.teal,C.tealBg)}${txt(730,510,["REASON IN"],18,C.teal,900,22,"middle",true)}${txt(730,548,["DOCUMENTS"],23,C.ink,900,28,"middle",true)}${txt(730,595,["extract relevance"],17,C.muted,700,21,"middle")}${arrow(890,545,1050,545,C.teal)}${card(1050,470,250,150,C.green,C.paper)}${txt(1175,525,["FOCUSED"],18,C.green,900,22,"middle",true)}${txt(1175,565,["EVIDENCE"],23,C.ink,900,28,"middle",true)}${arrow(1300,545,1420,545,C.green)}${pill(1420,517,100,"context",C.maroon,C.redBg)}${caveat(315,750,970,"Focused extraction can omit key sources or preserve errors from retrieved documents.")}`); }
function renderDiagnostic(s: Slide) { const qs=[[250,475,"01","DIVERSITY",C.cobalt],[525,600,"02","FEEDBACK",C.teal],[800,475,"03","SELECTION",C.brown],[1075,600,"04","FAILURE",C.red],[1350,475,"05","STOPPING",C.maroon]] as const; return shell(`${header(s)}${qs.map(([x,y,n,label,color])=>`${card(x-115,y-80,230,160,color,C.paper)}${txt(x,y-35,[n],16,color,900,20,"middle",true)}${txt(x,y+15,[label],17,color,900,21,"middle",true)}${txt(x,y+50,[label==="FAILURE"?"when wrong?":label==="STOPPING"?"when enough?":"make visible"],15,C.ink,650,19,"middle")}`).join("")}${arrow(365,475,410,555,C.teal)}${arrow(640,555,685,475,C.teal)}${arrow(915,475,960,555,C.teal)}${arrow(1190,555,1235,475,C.teal)}${card(510,750,580,62,C.cobalt,C.blueBg)}${txt(800,789,["BOUNDED SEARCH  !=  UNBOUNDED TRUST"],19,C.cobalt,900,23,"middle",true)}`); }

const renderers: Record<string,(s:Slide)=>string> = { cover:renderCover, pipeline:renderPipeline, fan:renderFan, compare:renderCompare, curve:renderCurve, family:renderFamily, metrics:renderMetrics, router:renderRouter, chain:renderChain, loop:renderLoop, docs:renderDocs, diagnostic:renderDiagnostic };

function prompt(slide: Slide, index: number) { return `# Slide ${index + 1}: ${slide.title.join(" ")}\n\n## Production method\nRendered locally as an original 1600x900 SVG for exact text fidelity, then converted to PNG. Do not reproduce Stanford frames, figures, or logos.\n\n## Style\nAged-cream academic technical briefing, faint engineering grid, crisp vector diagrams, near-black type, cobalt generation, teal verification, warm-brown budget, maroon constraints, 8px card corners, no gradients.\n\n## On-slide content\n- Stage: ${slide.stage}\n- Headline: ${slide.title.join(" ")}\n- Subtitle: ${slide.subtitle}\n- Supporting labels: ${slide.labels.join("; ")}\n- Evidence: CS329A Part 7, ${slide.evidence}\n\n## Visual direction\n${slide.visual}\n\n## Teaching objective\n${slide.objective}\n\n## Speaker notes\n${slide.notes}\n`; }

function contactSheet() { const tw=480,th=270,gap=26,margin=34,cols=3,rows=Math.ceil(slides.length/cols),cw=margin*2+cols*tw+(cols-1)*gap,ch=margin*2+rows*(th+42)+(rows-1)*gap; const images=slides.map((s,i)=>{const x=margin+(i%cols)*(tw+gap),y=margin+Math.floor(i/cols)*(th+42+gap),data=readFileSync(join(DIR,`${s.file}.png`)).toString("base64");return `<image href="data:image/png;base64,${data}" x="${x}" y="${y}" width="${tw}" height="${th}"/><text class="ui" x="${x}" y="${y+th+28}" font-size="17" font-weight="750" fill="${C.ink}">${String(i+1).padStart(2,"0")}  ${esc(s.title.join(" "))}</text>`;}).join(""); return `<svg xmlns="http://www.w3.org/2000/svg" width="${cw}" height="${ch}" viewBox="0 0 ${cw} ${ch}"><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}</style><rect width="${cw}" height="${ch}" fill="#E8E2D7"/>${images}</svg>`; }

ensure(SVG_DIR); ensure(PROMPT_DIR);
slides.forEach((slide,i)=>{ const svg=renderers[slide.kind](slide); const svgPath=join(SVG_DIR,`${slide.file}.svg`); const pngPath=join(DIR,`${slide.file}.png`); writeFileSync(svgPath,svg); writeFileSync(join(PROMPT_DIR,`${slide.file}.md`),prompt(slide,i)); const result=Bun.spawnSync(["sips","-s","format","png",svgPath,"--out",pngPath],{stdout:"pipe",stderr:"pipe"}); if(result.exitCode!==0) throw new Error(`sips failed for ${slide.file}: ${result.stderr.toString()}`); });
const sheetSvg=join(DIR,"contact-sheet.svg"); writeFileSync(sheetSvg,contactSheet()); const sheet=Bun.spawnSync(["sips","-s","format","png",sheetSvg,"--out",join(DIR,"contact-sheet.png")],{stdout:"pipe",stderr:"pipe"}); if(sheet.exitCode!==0) throw new Error(`sips failed for contact sheet: ${sheet.stderr.toString()}`);
console.log(`Rendered ${slides.length} slides, SVGs, prompts, and contact sheet in ${DIR}`);
