import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const SVG_DIR = join(DIR, "svgs");
const PROMPT_DIR = join(DIR, "prompts");
const W = 1600;
const H = 900;
const C = { bg: "#F5F0E6", paper: "#FFFCF4", ink: "#171717", muted: "#5E6670", line: "#D8D0C0", teal: "#2F7373", maroon: "#722F37", brown: "#8B7355", cobalt: "#2563EB", red: "#B42318", green: "#16803C", amber: "#B7791F", blueBg: "#F3F7FF", tealBg: "#F2FBF8", redBg: "#FFF5F3", amberBg: "#FFF9E8" };

type Slide = { file: string; stage: string; title: string[]; subtitle: string; evidence: string; objective: string; notes: string; visual: string };
const slides: Slide[] = [
  { file: "01-slide-cover", stage: "robust verification", title: ["A Generator Is Only", "as Useful as Its Selector"], subtitle: "Candidate coverage may rise while selected-answer accuracy stays flat or falls.", evidence: "00:09-00:52 / 14:19-18:24", objective: "Separate generated coverage from selected-answer reliability.", notes: "Repeated sampling expands the candidate set. Robust verification decides whether that latent capability becomes a correct returned answer. Ask Q why pass@k can rise while selected-answer accuracy falls.", visual: "Rising oracle-coverage curve beside a peaking selected-answer curve, connected to one generator and noisy selector." },
  { file: "02-slide-verifier-loop", stage: "outcome verifier", title: ["The Basic Verifier Loop Learns", "to Rerank Completed Solutions"], subtitle: "Generate, label, train a scalar verifier, then return the highest-scoring candidate.", evidence: "03:18-07:57 + arXiv:2110.14168", objective: "Explain the generate-label-train-rerank loop.", notes: "Candidates are labeled by final correctness. A verifier specializes in ranking while the generator remains general. Passing the verifier is still not proof of correctness.", visual: "Five-stage pipeline: question, generator, labeled candidates, verifier training, reranked output." },
  { file: "03-slide-false-positive-extremes", stage: "selection reversal", title: ["More Candidates Create More", "False-Positive Opportunities"], subtitle: "The maximum noisy score becomes less trustworthy unless verifier precision scales too.", evidence: "14:19-18:24", objective: "Explain why best-of-N selection can reverse.", notes: "More candidates increase the chance of a correct answer and of an extreme verifier error. The displayed peak around 400 candidates belongs to one historical setup, not a universal optimum.", visual: "One correct candidate competes against increasingly extreme wrong-candidate scores as N grows." },
  { file: "04-slide-orm-prm", stage: "credit assignment", title: ["Outcome Scores Judge the Finish;", "Process Scores Judge the Route"], subtitle: "PRMs add step-level credit assignment to a final-answer signal.", evidence: "21:17-25:06 + arXiv:2305.20050", objective: "Distinguish outcome and process reward models.", notes: "An ORM scores the full trajectory. A PRM scores intermediate steps and can expose a wrong chain that reaches the right final answer by luck.", visual: "The same reasoning chain shown once with a terminal score and once with scores on every step." },
  { file: "05-slide-process-rubric", stage: "human supervision", title: ["Process Labels Are Richer,", "but They Encode a Rubric"], subtitle: "Correctness, relevance, and sufficient justification depend on an annotation policy.", evidence: "25:06-28:32 / 31:43-37:51", objective: "Explain why process scores are not objective truth.", notes: "Human labels make reasoning inspectable, but they endorse a particular standard of acceptable reasoning. Valid shortcuts or unfamiliar methods may be penalized.", visual: "One reasoning step inspected through three rubric lenses: correctness, relevance, sufficiency." },
  { file: "06-slide-active-learning", stage: "label efficiency", title: ["PRM800K Targets Informative Mistakes", "Instead of Labeling Uniformly"], subtitle: "Active selection concentrates annotation near uncertain and convincing wrong solutions.", evidence: "26:11-30:14 + arXiv:2305.20050", objective: "Explain active selection and its comparison caveat.", notes: "Active learning can improve annotation efficiency by surfacing informative mistakes. It also changes the training distribution, so ORM and PRM label counts are not direct cost matches.", visual: "Uniform labels spread across a field versus active labels concentrated at a decision boundary." },
  { file: "07-slide-rollout-labels", stage: "automatic supervision", title: ["Automatic Process Labels Trade", "Human Cost for Rollout Compute"], subtitle: "A prefix is judged by sampled continuations that reach the correct final answer.", evidence: "37:51-40:42 + arXiv:2312.08935", objective: "Derive hard and soft rollout labels.", notes: "Hard label is positive if any continuation succeeds. Soft label is the success fraction. The estimate reflects both prefix quality and rollout-policy capability.", visual: "A reasoning prefix branches into successful and failed continuations with hard and soft formulas." },
  { file: "08-slide-rollout-failures", stage: "label noise", title: ["Rollout Labels Inherit", "the Search Policy's Blind Spots"], subtitle: "Good rare paths can look bad; wrong steps can look good after a lucky repair.", evidence: "40:42-43:27", objective: "Identify two automatic-label failure modes.", notes: "A finite rollout budget may miss a rare valid completion. A wrong intermediate step may later be repaired and receive positive credit. Ask whether rollout labels measure truth, search potential, or both.", visual: "Two counterexamples side by side: rare valid branch missed and invalid branch accidentally repaired." },
  { file: "09-slide-rerank-rl", stage: "verification feedback", title: ["Verification Can Select Outputs", "and Train the Generator"], subtitle: "The same PRM can guide inference-time reranking and PPO-style policy updates.", evidence: "43:27-47:41 + arXiv:2312.08935", objective: "Connect verification at inference to training-time feedback.", notes: "A PRM can rank candidates and become a training reward. Optimizing an incomplete proxy introduces reward-hacking risk.", visual: "A central PRM sends one branch to a selector and another into an RL update loop." },
  { file: "10-slide-weaver", stage: "weak verifier ensemble", title: ["Diversity Across Verifiers Helps", "Only After Weighting and Filtering"], subtitle: "Weaver normalizes heterogeneous scores, removes poor verifiers, and combines weighted evidence.", evidence: "51:51-57:36 + arXiv:2506.18203", objective: "Explain Weaver's score-weight-select pipeline.", notes: "Weak means imperfect. Adding verifiers naively is not monotonically useful because sources differ in quality. Normalize, filter, estimate reliability, weight, then select.", visual: "Four heterogeneous verifier score streams pass through normalization, filtering, weighting, and selection." },
  { file: "11-slide-dependence", stage: "ensemble assumptions", title: ["Shared Blind Spots Can Defeat", "an Entire Verifier Ensemble"], subtitle: "Complementary errors add evidence; correlated errors repeat the same mistake.", evidence: "57:36-60:07 + arXiv:2506.18203", objective: "Explain why dependence and quality gates matter.", notes: "Ten verifiers with one shared blind spot can behave like one verifier repeated ten times. Weighting cannot create independent evidence that does not exist.", visual: "Complementary verifier errors on the left; synchronized correlated error on the right." },
  { file: "12-slide-budget-system", stage: "end-to-end design", title: ["Design Verification as a", "Budgeted End-to-End System"], subtitle: "Evaluate selection accuracy, calibration, transfer, cost, and coverage together.", evidence: "60:07-68:13", objective: "Apply a reusable verification-system checklist.", notes: "Allocate compute across candidate count, generator strength, verifier strength and count, and distillation. Exit question: which bottleneck dominates the task—coverage, discrimination, shift, proxy, or cost?", visual: "Four budget dials around selected-answer accuracy and a bridge to Part 4 feedback with tools and code." },
];

function ensure(path: string) { if (!existsSync(path)) mkdirSync(path, { recursive: true }); }
function esc(s: string) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function measure(s: string) { return [...s].reduce((n, ch) => n + (/[^\x00-\x7F]/.test(ch) ? 1.7 : 1), 0); }
function wrap(s: string, max: number) { const out: string[] = []; let line = ""; for (const word of s.split(/\s+/)) { const next = line ? `${line} ${word}` : word; if (line && measure(next) > max) { out.push(line); line = word; } else line = next; } if (line) out.push(line); return out; }
function txt(x: number, y: number, lines: string[], size: number, color = C.ink, weight = 700, lh = Math.round(size * 1.18), anchor: "start" | "middle" = "start", mono = false) { return lines.map((line, i) => `<text class="${mono ? "mono" : "ui"}" x="${x}" y="${y + i * lh}" fill="${color}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}">${esc(line)}</text>`).join(""); }
function card(x: number, y: number, w: number, h: number, stroke = C.line, fill = C.paper, rx = 8) { return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`; }
function arrow(x1: number, y1: number, x2: number, y2: number, color = C.teal, width = 4, dash = "") { return `<path d="M${x1} ${y1} L${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ""} marker-end="url(#arrow)"/>`; }
function pill(x: number, y: number, w: number, label: string, color = C.teal, fill = C.paper) { return `${card(x, y, w, 56, color, fill)}${txt(x + w / 2, y + 36, [label], 19, color, 850, 23, "middle", true)}`; }
function shell(inner: string) { return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><pattern id="grid" width="46" height="46" patternUnits="userSpaceOnUse"><path d="M46 0 L0 0 0 46" fill="none" stroke="${C.line}" stroke-width="1" opacity="0.38"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="context-stroke"/></marker></defs><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Inter","Segoe UI",Arial,sans-serif;letter-spacing:0}.mono{font-family:"SFMono-Regular","SF Mono",Consolas,monospace;letter-spacing:0}</style><rect width="${W}" height="${H}" fill="${C.bg}"/><rect width="${W}" height="${H}" fill="url(#grid)"/><rect x="42" y="42" width="1516" height="816" rx="8" fill="${C.paper}" opacity="0.9"/>${inner}</svg>`; }
function badge(s: Slide) { const w = Math.max(220, measure(s.stage) * 11 + 50); return `${card(84, 68, w, 43, C.teal, C.tealBg)}${txt(108, 97, [s.stage.toUpperCase()], 16, C.teal, 900, 20, "start", true)}`; }
function evidence(s: Slide) { const label = `PART 3  ${s.evidence}`; const w = Math.max(270, measure(label) * 10 + 40); return `${card(1516 - w, 68, w, 43, C.line, C.paper)}${txt(1516 - w / 2, 97, [label], 15, C.muted, 780, 19, "middle", true)}`; }
function header(s: Slide) { return `${badge(s)}${evidence(s)}${txt(86, 188, s.title, 51, C.ink, 920, 58)}${txt(90, 188 + s.title.length * 58 + 20, wrap(s.subtitle, 86), 23, C.muted, 560, 29)}`; }
function caveat(x: number, y: number, w: number, label: string) { const lines = wrap(label, Math.floor(w / 13)); return `${card(x, y, w, 42 + lines.length * 27, C.red, C.redBg)}${txt(x + 20, y + 28, ["CAVEAT"], 15, C.red, 900, 19, "start", true)}${txt(x + 20, y + 57, lines, 20, C.ink, 640, 27)}`; }

function render1(s: Slide) {
  const coverage = `<path d="M850 680 C970 610 1080 520 1450 425" fill="none" stroke="${C.cobalt}" stroke-width="7"/>`;
  const selected = `<path d="M850 680 C1000 590 1130 475 1250 485 C1350 500 1400 580 1450 650" fill="none" stroke="${C.maroon}" stroke-width="7"/>`;
  return shell(`${badge(s)}${evidence(s)}${txt(90, 240, s.title, 66, C.ink, 930, 76)}${txt(94, 450, wrap(s.subtitle, 42), 26, C.muted, 560, 34)}${pill(95, 660, 220, "Generate more", C.cobalt, C.blueBg)}${arrow(315, 688, 500, 688, C.teal)}${pill(500, 660, 190, "Select one", C.maroon, C.redBg)}${card(790, 350, 720, 390, C.teal, C.paper)}${coverage}${selected}${txt(1140, 395, ["ORACLE COVERAGE"], 17, C.cobalt, 900, 21, "middle", true)}${txt(1320, 700, ["SELECTED ACCURACY"], 17, C.maroon, 900, 21, "middle", true)}${txt(1140, 755, ["candidate count  ->"], 18, C.muted, 740, 22, "middle", true)}`);
}

function render2(s: Slide) {
  const steps = [
    [85, "QUESTION", "task", C.cobalt], [360, "GENERATE", "100 candidates", C.cobalt], [660, "LABEL", "final correctness", C.brown], [960, "TRAIN", "scalar verifier", C.teal], [1260, "RERANK", "return top score", C.maroon],
  ] as const;
  return shell(`${header(s)}${steps.map(([x, a, b, color], i) => `${card(x, 450, 240, 190, color, C.paper)}${txt(x + 120, 505, [a], 20, color, 900, 24, "middle", true)}${txt(x + 120, 565, wrap(b, 18), 22, C.ink, 720, 28, "middle")}${i < 4 ? arrow(x + 240, 545, x + 275, 545, C.teal) : ""}`).join("")}${caveat(430, 720, 740, "A learned correctness score is evidence for ranking, not proof that the selected answer is true.")}`);
}

function render3(s: Slide) {
  const dots = Array.from({ length: 27 }, (_, i) => { const x = 825 + (i % 9) * 72; const y = 450 + Math.floor(i / 9) * 80; const correct = i === 10; const extreme = i === 25; return `<circle cx="${x}" cy="${y}" r="23" fill="${correct ? C.green : extreme ? C.red : C.line}" opacity="${correct || extreme ? 1 : 0.74}"/>${correct ? txt(x, y + 6, ["OK"], 12, "#fff", 900, 15, "middle", true) : extreme ? txt(x, y + 6, ["MAX"], 10, "#fff", 900, 13, "middle", true) : ""}`; }).join("");
  return shell(`${header(s)}${card(90, 420, 570, 300, C.cobalt, C.blueBg)}${txt(135, 475, ["AS N GROWS"], 20, C.cobalt, 900, 24, "start", true)}${txt(135, 535, wrap("chance of a correct candidate rises", 30), 26, C.ink, 800, 33)}${txt(135, 630, wrap("chance of an extreme verifier false positive rises too", 32), 24, C.maroon, 800, 31)}${card(750, 400, 765, 340, C.maroon, C.paper)}${txt(790, 445, ["NOISY SCORE COMPETITION"], 19, C.maroon, 900, 23, "start", true)}${dots}${txt(1130, 710, ["green exists  !=  red wins"], 18, C.red, 850, 22, "middle", true)}${caveat(410, 785, 780, "The roughly 400-candidate peak shown in the lecture is setup-specific, not a universal optimum.")}`);
}

function render4(s: Slide) {
  const chain = ["step 1", "step 2", "step 3", "answer"];
  return shell(`${header(s)}${card(80, 410, 670, 330, C.maroon, C.redBg)}${txt(415, 465, ["OUTCOME REWARD MODEL"], 21, C.maroon, 900, 25, "middle", true)}${chain.map((label, i) => `${pill(120 + i * 150, 545, 120, label, C.maroon, C.paper)}${i < 3 ? arrow(240 + i * 150, 573, 270 + i * 150, 573, C.maroon, 3) : ""}`).join("")}${pill(500, 650, 170, "final: 0.78", C.maroon, C.paper)}${card(850, 410, 670, 330, C.teal, C.tealBg)}${txt(1185, 465, ["PROCESS REWARD MODEL"], 21, C.teal, 900, 25, "middle", true)}${chain.map((label, i) => `${pill(890 + i * 150, 545, 120, label, C.teal, C.paper)}${i < 3 ? arrow(1010 + i * 150, 573, 1040 + i * 150, 573, C.teal, 3) : ""}${txt(950 + i * 150, 640, [["0.9", "0.3", "0.8", "0.7"][i]], 18, i === 1 ? C.red : C.teal, 900, 22, "middle", true)}`).join("")}${txt(800, 800, ["Terminal credit  <->  step-level credit assignment"], 21, C.muted, 800, 25, "middle", true)}`);
}

function render5(s: Slide) {
  const lenses = [[310, "CORRECT?", "factual / logical", C.green], [800, "RELEVANT?", "advances the solution", C.cobalt], [1290, "SUFFICIENT?", "justified enough", C.maroon]] as const;
  return shell(`${header(s)}${card(620, 405, 360, 145, C.brown, C.amberBg)}${txt(800, 460, ["REASONING STEP"], 21, C.brown, 900, 25, "middle", true)}${txt(800, 510, ["valid shortcut?"], 24, C.ink, 750, 29, "middle")}${lenses.map(([x, label, desc, color]) => `${arrow(800, 550, x, 625, color, 3)}${card(x - 190, 625, 380, 145, color, C.paper)}${txt(x, 675, [label], 20, color, 900, 24, "middle", true)}${txt(x, 720, [desc], 21, C.ink, 680, 25, "middle")}`).join("")}${caveat(410, 805, 780, "A process label encodes an annotation policy and may reject valid alternative reasoning styles.")}`);
}

function render6(s: Slide) {
  const field = Array.from({ length: 42 }, (_, i) => { const x = 900 + (i % 7) * 80; const y = 420 + Math.floor(i / 7) * 55; const active = [9, 10, 16, 17, 18, 23, 24, 25, 31, 32].includes(i); return `<circle cx="${x}" cy="${y}" r="${active ? 16 : 10}" fill="${active ? C.maroon : C.line}" opacity="${active ? 1 : 0.75}"/>`; }).join("");
  return shell(`${header(s)}${card(80, 415, 600, 325, C.cobalt, C.blueBg)}${txt(380, 470, ["UNIFORM LABELING"], 21, C.cobalt, 900, 25, "middle", true)}${Array.from({ length: 24 }, (_, i) => `<circle cx="${145 + (i % 6) * 85}" cy="${545 + Math.floor(i / 6) * 55}" r="13" fill="${C.cobalt}" opacity="0.7"/>`).join("")}${txt(380, 710, ["spread annotation everywhere"], 19, C.muted, 700, 23, "middle")}${card(780, 395, 740, 365, C.maroon, C.redBg)}${txt(1150, 445, ["ACTIVE SELECTION"], 21, C.maroon, 900, 25, "middle", true)}${field}<path d="M850 705 C980 620 1100 530 1460 410" fill="none" stroke="${C.brown}" stroke-width="4" stroke-dasharray="10 8"/>${txt(1150, 735, ["uncertain + convincing wrong"], 19, C.muted, 700, 23, "middle")}${caveat(420, 800, 760, "Active selection changes the training distribution and complicates direct label-budget comparisons.")}`);
}

function render7(s: Slide) {
  const branches = [[880, 450, true], [1040, 520, false], [1200, 590, true], [1360, 660, false]] as const;
  return shell(`${header(s)}${pill(110, 535, 250, "reasoning prefix", C.cobalt, C.blueBg)}${arrow(360, 563, 620, 563, C.cobalt, 5)}${card(620, 485, 190, 155, C.brown, C.amberBg)}${txt(715, 535, ["ROLLOUT"], 20, C.brown, 900, 24, "middle", true)}${txt(715, 580, ["sample N"], 22, C.ink, 700, 26, "middle")}${branches.map(([x, y, ok]) => `${arrow(810, 563, x - 55, y, ok ? C.teal : C.maroon, 3)}<circle cx="${x}" cy="${y}" r="40" fill="${ok ? C.tealBg : C.redBg}" stroke="${ok ? C.green : C.red}" stroke-width="3"/>${txt(x, y + 7, [ok ? "OK" : "FAIL"], 14, ok ? C.green : C.red, 900, 17, "middle", true)}`).join("")}${card(945, 720, 520, 85, C.teal, C.paper)}${txt(1205, 754, ["hard = any success     soft = success / N"], 19, C.teal, 850, 23, "middle", true)}`);
}

function render8(s: Slide) {
  return shell(`${header(s)}${card(80, 410, 680, 340, C.cobalt, C.blueBg)}${txt(420, 465, ["RARE VALID PATH MISSED"], 21, C.cobalt, 900, 25, "middle", true)}${pill(135, 565, 180, "good prefix", C.green, C.paper)}${arrow(315, 593, 450, 520, C.green, 3, "9 7")}${arrow(315, 593, 450, 665, C.red, 3)}${pill(450, 492, 210, "rare success", C.green, C.paper)}${pill(450, 637, 210, "sampled fails", C.red, C.paper)}${txt(420, 720, ["false negative label"], 19, C.red, 800, 23, "middle")}${card(840, 410, 680, 340, C.maroon, C.redBg)}${txt(1180, 465, ["WRONG STEP LUCKILY REPAIRED"], 21, C.maroon, 900, 25, "middle", true)}${pill(895, 565, 180, "bad prefix", C.red, C.paper)}${arrow(1075, 593, 1210, 593, C.teal, 3)}${pill(1210, 565, 220, "lucky correction", C.teal, C.paper)}${txt(1180, 720, ["false positive label"], 19, C.red, 800, 23, "middle")}${caveat(470, 800, 660, "Rollout labels mix prefix quality with the capability and luck of the rollout policy.")}`);
}

function render9(s: Slide) {
  return shell(`${header(s)}${card(600, 430, 400, 170, C.teal, C.tealBg)}${txt(800, 485, ["PROCESS REWARD MODEL"], 21, C.teal, 900, 25, "middle", true)}${txt(800, 540, ["step quality proxy"], 23, C.ink, 720, 27, "middle")}${arrow(600, 515, 360, 515, C.teal, 5)}${card(90, 425, 270, 180, C.cobalt, C.blueBg)}${txt(225, 478, ["INFERENCE"], 20, C.cobalt, 900, 24, "middle", true)}${txt(225, 530, ["rerank candidates"], 21, C.ink, 700, 25, "middle")}${arrow(1000, 515, 1240, 515, C.maroon, 5)}${card(1240, 425, 270, 180, C.maroon, C.redBg)}${txt(1375, 478, ["TRAINING"], 20, C.maroon, 900, 24, "middle", true)}${txt(1375, 530, ["PPO reward"], 21, C.ink, 700, 25, "middle")}${arrow(1375, 605, 1375, 700, C.maroon, 3)}${arrow(1375, 700, 1010, 700, C.maroon, 3)}${arrow(1010, 700, 1010, 600, C.maroon, 3)}${caveat(430, 745, 740, "Optimizing an imperfect reward model can raise the proxy score without improving correctness.")}`);
}

function render10(s: Slide) {
  const sources = [[75, "RM-A", C.cobalt], [75, "RM-B", C.brown], [75, "JUDGE-C", C.maroon], [75, "JUDGE-D", C.teal]] as const;
  const stages = [[430, "NORMALIZE", C.cobalt], [700, "FILTER", C.red], [970, "WEIGHT", C.brown], [1240, "SELECT", C.teal]] as const;
  return shell(`${header(s)}${sources.map(([x, label, color], i) => `${pill(x, 415 + i * 76, 220, label, color, C.paper)}${arrow(295, 443 + i * 76, 410, 555, color, 3)}`).join("")}${stages.map(([x, label, color], i) => `${card(x, 465, 220, 180, color, i === 3 ? C.tealBg : C.paper)}${txt(x + 110, 520, [label], 19, color, 900, 23, "middle", true)}${txt(x + 110, 575, wrap(["common scale", "drop poor", "estimate trust", "one answer"][i], 14), 21, C.ink, 700, 26, "middle")}${i < 3 ? arrow(x + 220, 555, x + 270, 555, C.teal) : ""}`).join("")}${caveat(390, 735, 820, "Adding more verifiers naively is not monotonically useful; sources differ in quality and bias.")}`);
}

function render11(s: Slide) {
  const left = [[220, 545], [360, 500], [500, 595]].map(([x, y], i) => `<circle cx="${x}" cy="${y}" r="42" fill="${[C.cobalt, C.teal, C.brown][i]}"/><path d="M${x - 18} ${y} l12 12 l26 -28" fill="none" stroke="#fff" stroke-width="6"/>`).join("");
  const right = [[1000, 505], [1160, 555], [1320, 605]].map(([x, y]) => `<circle cx="${x}" cy="${y}" r="42" fill="${C.maroon}"/><path d="M${x - 17} ${y - 17} l34 34 M${x + 17} ${y - 17} l-34 34" stroke="#fff" stroke-width="6"/>`).join("");
  return shell(`${header(s)}${card(80, 410, 650, 335, C.teal, C.tealBg)}${txt(405, 465, ["COMPLEMENTARY ERRORS"], 21, C.teal, 900, 25, "middle", true)}${left}${txt(405, 705, ["different evidence adds value"], 19, C.muted, 700, 23, "middle")}${card(870, 410, 650, 335, C.maroon, C.redBg)}${txt(1195, 465, ["CORRELATED BLIND SPOT"], 21, C.maroon, 900, 25, "middle", true)}${right}${txt(1195, 705, ["same mistake repeated"], 19, C.muted, 700, 23, "middle")}${caveat(455, 790, 690, "Weighting cannot create independent evidence when every verifier shares the same failure.")}`);
}

function render12(s: Slide) {
  const dials = [[250, "CANDIDATES", "coverage", C.cobalt], [610, "GENERATOR", "capability", C.brown], [990, "VERIFIERS", "discrimination", C.teal], [1350, "DISTILL", "serving cost", C.maroon]] as const;
  return shell(`${header(s)}${dials.map(([x, label, desc, color]) => `${circleDial(x, 510, color)}${txt(x, 610, [label], 18, color, 900, 22, "middle", true)}${txt(x, 650, [desc], 19, C.muted, 680, 23, "middle")}`).join("")}${card(490, 710, 620, 75, C.green, C.tealBg)}${txt(800, 757, ["SELECTED-ANSWER ACCURACY + CALIBRATION + COST"], 19, C.green, 900, 23, "middle", true)}${txt(800, 825, ["NEXT: PART 4 - LEARNING FROM FEEDBACK WITH TOOLS AND CODE"], 18, C.cobalt, 850, 22, "middle", true)}`);
}
function circleDial(x: number, y: number, color: string) { return `<circle cx="${x}" cy="${y}" r="70" fill="${C.paper}" stroke="${color}" stroke-width="5"/><path d="M${x} ${y} L${x + 38} ${y - 38}" stroke="${color}" stroke-width="7" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r="9" fill="${color}"/>`; }

const renderers = [render1, render2, render3, render4, render5, render6, render7, render8, render9, render10, render11, render12];
function prompt(s: Slide, i: number) { return `# Slide ${i + 1}: ${s.title.join(" ")}\n\n## Production\nOriginal 1600x900 local SVG rendered to PNG. Do not reproduce Stanford frames or logos.\n\n## Style\nAged-cream technical briefing, faint grid, crisp vector control diagrams, cobalt generation, teal verification, maroon failure, brown supervision, no gradients.\n\n## Content\n- Stage: ${s.stage}\n- Headline: ${s.title.join(" ")}\n- Subtitle: ${s.subtitle}\n- Evidence: CS329A Part 3, ${s.evidence}\n\n## Visual\n${s.visual}\n\n## Objective\n${s.objective}\n\n## Speaker notes\n${s.notes}\n`; }
function contactSheet() { const tw = 480, th = 270, gap = 26, margin = 34, cols = 3, rows = 4, cw = margin * 2 + cols * tw + 2 * gap, ch = margin * 2 + rows * (th + 42) + 3 * gap; const imgs = slides.map((s, i) => { const x = margin + (i % cols) * (tw + gap), y = margin + Math.floor(i / cols) * (th + 42 + gap), data = readFileSync(join(DIR, `${s.file}.png`)).toString("base64"); return `<image href="data:image/png;base64,${data}" x="${x}" y="${y}" width="${tw}" height="${th}"/><text class="ui" x="${x}" y="${y + th + 28}" font-size="17" font-weight="750" fill="${C.ink}">${String(i + 1).padStart(2, "0")}  ${esc(s.title.join(" "))}</text>`; }).join(""); return `<svg xmlns="http://www.w3.org/2000/svg" width="${cw}" height="${ch}" viewBox="0 0 ${cw} ${ch}"><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}</style><rect width="100%" height="100%" fill="#E8E2D7"/>${imgs}</svg>`; }

ensure(SVG_DIR); ensure(PROMPT_DIR);
slides.forEach((s, i) => { const svg = renderers[i](s); const svgPath = join(SVG_DIR, `${s.file}.svg`); writeFileSync(svgPath, svg); writeFileSync(join(PROMPT_DIR, `${s.file}.md`), prompt(s, i)); const out = Bun.spawnSync(["sips", "-s", "format", "png", svgPath, "--out", join(DIR, `${s.file}.png`)], { stdout: "pipe", stderr: "pipe" }); if (out.exitCode !== 0) throw new Error(out.stderr.toString()); });
const sheetSvg = join(DIR, "contact-sheet.svg"); writeFileSync(sheetSvg, contactSheet()); const sheet = Bun.spawnSync(["sips", "-s", "format", "png", sheetSvg, "--out", join(DIR, "contact-sheet.png")], { stdout: "pipe", stderr: "pipe" }); if (sheet.exitCode !== 0) throw new Error(sheet.stderr.toString());
console.log(`Rendered ${slides.length} slides and prompts in ${DIR}`);
