import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const SVG_DIR = join(DIR, "svgs");
const PROMPT_DIR = join(DIR, "prompts");
const W = 1600;
const H = 900;

const C = {
  bg: "#F5F0E6", paper: "#FFFCF4", ink: "#171717", muted: "#5E6670",
  line: "#D8D0C0", teal: "#2F7373", maroon: "#722F37", brown: "#8B7355",
  cobalt: "#2563EB", red: "#B42318", green: "#16803C", amber: "#B7791F",
  blueBg: "#F3F7FF", tealBg: "#F2FBF8", redBg: "#FFF5F3", amberBg: "#FFF9E8",
};

type Slide = {
  file: string; stage: string; title: string[]; subtitle: string; labels: string[];
  evidence: string; objective: string; notes: string; visual: string; kind: string;
};

const slides: Slide[] = [
  { file: "01-slide-cover", stage: "evaluation portfolio", title: ["One Benchmark Cannot", "Certify an Agent"], subtitle: "Stanford CS329A Part 8 - duration, economic value, and evidence quality", labels: ["Duration", "Value", "Evidence"], evidence: "00:00-04:32 / synthesis", objective: "Frame evaluation as a portfolio of distinct claims.", notes: "A benchmark observes one task distribution under one protocol. Deployment adds context, cost, interaction, and long-tail failure. Ask which claim each test can actually support.", visual: "Three independent gauges feed a bounded deployment judgment.", kind: "cover" },
  { file: "02-slide-three-axes", stage: "construct separation", title: ["Agent Progress Has at Least", "Three Independent Axes"], subtitle: "Longer tasks, valuable deliverables, and grounded synthesis are not interchangeable.", labels: ["Duration", "Economic value", "Evidence quality"], evidence: "00:00-04:32 + 61:03-68:20", objective: "Separate three evaluation constructs before discussing scores.", notes: "A system may improve on one axis while remaining weak on another. Do not average these into a universal capability number.", visual: "Three orthogonal measurement rulers with distinct observables and blind spots.", kind: "axes" },
  { file: "03-slide-time-horizon", stage: "reliability boundary", title: ["A Time Horizon Is a Fitted", "Reliability Boundary"], subtitle: "Human completion time is a proxy; the horizon is a threshold intersection.", labels: ["Task duration", "Success probability", "50% horizon"], evidence: "04:32-16:55 + METR v4", objective: "Explain how METR's time horizon is constructed.", notes: "The horizon is not the longest task an agent happened to complete. It comes from a fitted success curve over tasks binned by skilled-human completion time.", visual: "Task observations, descending fitted success curve, and a labeled 50 percent intersection.", kind: "horizon" },
  { file: "04-slide-threshold-choice", stage: "metric sensitivity", title: ["Changing the Reliability Target", "Changes the Horizon"], subtitle: "A 50% horizon and an 80% horizon answer different deployment questions.", labels: ["50%", "80%", "Same model", "Different claim"], evidence: "16:55-22:55 + METR v4", objective: "Make the success threshold visible as a policy choice.", notes: "Higher required reliability produces a shorter horizon on the same fitted curve. Always state the threshold before comparing systems.", visual: "One success curve crossed by two horizontal reliability lines at different durations.", kind: "thresholds" },
  { file: "05-slide-historical-trend", stage: "external validity", title: ["The Seven-Month Trend Is Historical,", "Not a Deployment Forecast"], subtitle: "Observed benchmark scaling does not remove task-distribution or future-trend uncertainty.", labels: ["Historical fit", "~7 months", "Not a forecast"], evidence: "16:55-22:10 + METR v4", objective: "Calibrate the interpretation of METR's historical doubling result.", notes: "METR reports an approximately seven-month historical doubling in the 50 percent horizon for the studied software-task family. The paper explicitly discusses external-validity limitations.", visual: "Dated historical points and a fitted line ending at an uncertainty wall rather than extending as a forecast.", kind: "trend" },
  { file: "06-slide-trajectory-failures", stage: "failure anatomy", title: ["Long Tasks Fail Through Trajectories,", "Not Only Final Answers"], subtitle: "Planning errors, recovery failures, loops, and abandonment compound over time.", labels: ["Plan", "Act", "Observe", "Recover"], evidence: "22:55-27:21 + METR", objective: "Shift evaluation from endpoint correctness to trajectory diagnostics.", notes: "Final success hides where the run failed. Long-horizon evaluation should preserve traces so evaluators can distinguish planning, execution, and recovery failures.", visual: "A task trace with branching failure points and an audit trail.", kind: "failures" },
  { file: "07-slide-gdpval-judgment", stage: "economic value", title: ["GDPval Changes the Question From", "Duration to Deliverable Value"], subtitle: "Experts compare realistic work products rather than only checking a final token or test.", labels: ["Work brief", "Model deliverable", "Reference", "Expert judge"], evidence: "27:21-33:40 + GDPval v1", objective: "Explain GDPval's pairwise expert-evaluation protocol.", notes: "The evaluation asks whether a model can produce economically valuable work products under the benchmark context. It does not measure entire jobs or deployment readiness.", visual: "A brief produces two deliverables that are compared by a domain expert.", kind: "gdpval" },
  { file: "08-slide-gdpval-sampling", stage: "sampling frame", title: ["GDPval Samples Work,", "Not Entire Occupations"], subtitle: "Nine sectors and 44 occupations define a broad but bounded task distribution.", labels: ["9 sectors", "44 occupations", "1,320 tasks", "220 open tasks"], evidence: "33:40-38:50 + GDPval v1", objective: "Attach GDPval findings to its task-sampling frame.", notes: "The benchmark contains 1,320 tasks, with a 220-task open set. Professionals average 14 years of experience. These tasks are evidence about sampled deliverables, not full occupational replacement.", visual: "A funnel from sectors to occupations to tasks to the open evaluation set.", kind: "sampling" },
  { file: "09-slide-aggregate-heterogeneity", stage: "aggregation risk", title: ["Aggregate Near-Parity Can Hide", "Uneven Capability"], subtitle: "A mean preference result can coexist with sharp task-by-task weaknesses.", labels: ["Aggregate", "Occupation", "Task", "Context"], evidence: "35:40-51:34 + GDPval v1", objective: "Prevent aggregate scores from becoming universal claims.", notes: "GDPval reports aggregate comparisons, but capability is heterogeneous across tasks and models. A near-parity aggregate is not task-by-task equivalence or job replacement.", visual: "One aggregate bar above a set of widely varying task-level bars.", kind: "heterogeneity" },
  { file: "10-slide-research-synthesis", stage: "evidence quality", title: ["Research Synthesis Needs", "Three Scores, Not One"], subtitle: "Synthesis quality, retrieval coverage, and citation support expose different errors.", labels: ["Synthesis", "Retrieval", "Verifiability"], evidence: "51:34-55:20 + DeepScholar v2", objective: "Explain the multi-dimensional evaluation of deep-research systems.", notes: "A fluent report can miss important sources or attach unsupported citations. These dimensions must stay separate to diagnose the failure.", visual: "A triangle of synthesis, retrieval, and verifiability with different failure examples.", kind: "triangle" },
  { file: "11-slide-version-boundary", stage: "version discipline", title: ["19% and 31% Are Different", "Version Snapshots, Not a Trend"], subtitle: "The Autumn 2025 lecture and February 2026 arXiv v2 use separately reported aggregates.", labels: ["Lecture: 19%", "arXiv v2: 31%", "Do not subtract"], evidence: "55:20 + arXiv:2508.20033v2", objective: "Preserve the DeepScholar-Bench version discrepancy without implying improvement.", notes: "The lecture says no system exceeded 19 percent across all metrics. The current v2 abstract says no system exceeds 31 percent geometric mean. Revisions may change systems, metric definitions, or aggregation. Do not connect or subtract the values.", visual: "Two dated snapshot cards separated by a red non-comparability wall.", kind: "versions" },
  { file: "12-slide-evaluation-portfolio", stage: "deployment audit", title: ["Match Every Deployment Claim to", "an Evaluation Portfolio"], subtitle: "State distribution, threshold, context, evidence, version, and missing dimensions.", labels: ["Claim", "Test", "Version", "Blind spot"], evidence: "whole lecture / synthesis", objective: "Apply a reusable evaluation audit to deployment claims.", notes: "No portfolio proves universal safety or capability. It makes the evidence boundary inspectable and identifies what still needs testing.", visual: "A claim-to-test matrix with an explicit blind-spot column.", kind: "portfolio" },
];

function ensure(path: string) { if (!existsSync(path)) mkdirSync(path, { recursive: true }); }
function esc(s: string) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function measure(s: string) { return [...s].reduce((n, ch) => n + (/[^\x00-\x7F]/.test(ch) ? 1.7 : 1), 0); }
function wrap(s: string, max: number) { const out: string[] = []; let line = ""; for (const word of s.split(/\s+/)) { const next = line ? `${line} ${word}` : word; if (measure(next) > max && line) { out.push(line); line = word; } else line = next; } if (line) out.push(line); return out; }
function txt(x: number, y: number, lines: string[], size: number, color = C.ink, weight = 700, lh = Math.round(size * 1.18), anchor: "start" | "middle" = "start", mono = false) { return lines.map((line, i) => `<text class="${mono ? "mono" : "ui"}" x="${x}" y="${y + i * lh}" fill="${color}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}">${esc(line)}</text>`).join(""); }
function card(x: number, y: number, w: number, h: number, stroke = C.line, fill = C.paper, rx = 8) { return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`; }
function arrow(x1: number, y1: number, x2: number, y2: number, color = C.teal, width = 4, dash = "") { return `<path d="M${x1} ${y1} L${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}" ${dash ? `stroke-dasharray="${dash}"` : ""} marker-end="url(#arrow)"/>`; }
function pill(x: number, y: number, w: number, label: string, color = C.teal, fill = C.paper) { return `${card(x, y, w, 56, color, fill)}${txt(x + w / 2, y + 35, [label], 18, color, 850, 22, "middle", true)}`; }
function shell(inner: string) { return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><pattern id="grid" width="46" height="46" patternUnits="userSpaceOnUse"><path d="M46 0 L0 0 0 46" fill="none" stroke="${C.line}" stroke-width="1" opacity="0.38"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="context-stroke"/></marker></defs><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Inter","Segoe UI",Arial,sans-serif;letter-spacing:0}.mono{font-family:"SFMono-Regular","SF Mono",Consolas,monospace;letter-spacing:0}</style><rect width="${W}" height="${H}" fill="${C.bg}"/><rect width="${W}" height="${H}" fill="url(#grid)"/><rect x="42" y="42" width="1516" height="816" rx="8" fill="${C.paper}" opacity="0.92"/>${inner}</svg>`; }
function badge(s: Slide) { const w = Math.max(220, measure(s.stage) * 12 + 54); return `${card(84, 68, w, 43, C.teal, C.tealBg)}${txt(108, 97, [s.stage.toUpperCase()], 17, C.teal, 900, 21, "start", true)}`; }
function evidence(s: Slide) { const label = `PART 8  ${s.evidence}`; const w = Math.min(650, Math.max(330, measure(label) * 9.4 + 42)); return `${card(1516 - w, 68, w, 43, C.line, C.paper)}${txt(1516 - w / 2, 97, [label], 15, C.muted, 760, 19, "middle", true)}`; }
function header(s: Slide) { return `${badge(s)}${evidence(s)}${txt(86, 188, s.title, 50, C.ink, 920, 57)}${txt(90, 188 + s.title.length * 57 + 18, wrap(s.subtitle, 91), 23, C.muted, 560, 29)}`; }
function caveat(x: number, y: number, w: number, label: string) { const lines = wrap(label, Math.floor(w / 12)); return `${card(x, y, w, 40 + lines.length * 25, C.red, C.redBg)}${txt(x + 18, y + 27, ["BOUNDARY"], 14, C.red, 900, 18, "start", true)}${txt(x + 18, y + 54, lines, 18, C.ink, 630, 25)}`; }

function renderCover(s: Slide) { const gauges=[[940,"DURATION",C.cobalt],[1140,"VALUE",C.brown],[1340,"EVIDENCE",C.teal]] as const; return shell(`${badge(s)}${evidence(s)}${txt(90,245,s.title,64,C.ink,930,74)}${txt(94,455,wrap(s.subtitle,38),25,C.muted,560,32)}${gauges.map(([x,label,color],i)=>`${card(x-80,385,160,185,color,C.paper)}<circle cx="${x}" cy="455" r="48" fill="none" stroke="${C.line}" stroke-width="12"/><path d="M${x-40} 472 A48 48 0 0 1 ${x+32-i*8} 420" fill="none" stroke="${color}" stroke-width="12" stroke-linecap="round"/>${txt(x,535,[label],15,color,900,19,"middle",true)}${arrow(x,570,1140,670,color,3)}`).join("")}${card(980,665,320,90,C.maroon,C.redBg)}${txt(1140,705,["BOUNDED JUDGMENT"],18,C.maroon,900,22,"middle",true)}${txt(1140,737,["not certification"],17,C.ink,700,21,"middle")}`); }
function renderAxes(s: Slide) { const items=[[100,"01","DURATION","success over human time","time is only a proxy",C.cobalt],[585,"02","ECONOMIC VALUE","expert preference","sampled work, not whole jobs",C.brown],[1070,"03","EVIDENCE QUALITY","grounded synthesis","coverage can remain hidden",C.teal]] as const; return shell(`${header(s)}${items.map(([x,n,a,b,c,color])=>`${card(x,410,430,300,color,C.paper)}${txt(x+38,462,[n],17,color,900,20,"start",true)}${txt(x+38,515,[a],22,color,900,27,"start",true)}${txt(x+38,574,wrap(b,28),22,C.ink,750,28)}${txt(x+38,665,wrap(c,32),17,C.red,700,23)}`).join("")}${caveat(355,760,890,"Improvement on one axis does not imply improvement on the other two.")}`); }
function fittedCurve() { return `<path d="M175 450 C360 460 520 500 680 585 C825 660 955 700 1115 720" fill="none" stroke="${C.cobalt}" stroke-width="7"/><path d="M150 735 L1170 735 M150 410 L150 735" fill="none" stroke="${C.ink}" stroke-width="3"/>`; }
function renderHorizon(s: Slide) { const dots=[[220,450],[310,478],[420,480],[520,535],[635,570],[730,630],[845,650],[960,710],[1080,695]].map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="10" fill="${i%2?C.teal:C.brown}" opacity=".8"/>`).join(""); return shell(`${header(s)}${card(90,390,1120,380,C.line,C.paper)}${fittedCurve()}${dots}<path d="M150 585 L680 585 L680 735" fill="none" stroke="${C.red}" stroke-width="3" stroke-dasharray="10 8"/>${txt(178,575,["50% SUCCESS"],16,C.red,900,20,"start",true)}${pill(570,748,220,"50% horizon",C.red,C.redBg)}${card(1250,430,250,225,C.teal,C.tealBg)}${txt(1375,482,["FIT"],17,C.teal,900,21,"middle",true)}${txt(1375,537,["success"],22,C.ink,850,27,"middle")}${txt(1375,572,["vs."],17,C.muted,700,21,"middle")}${txt(1375,607,["human time"],22,C.ink,850,27,"middle")}${caveat(390,790,820,"The horizon is a fitted threshold, not the longest observed success.")}`); }
function renderThresholds(s: Slide) { return shell(`${header(s)}${card(90,390,1190,385,C.line,C.paper)}${fittedCurve()}<path d="M150 500 L520 500 L520 735" fill="none" stroke="${C.maroon}" stroke-width="3" stroke-dasharray="10 8"/><path d="M150 585 L680 585 L680 735" fill="none" stroke="${C.red}" stroke-width="3" stroke-dasharray="10 8"/>${txt(175,492,["80%"],18,C.maroon,900,22,"start",true)}${txt(175,577,["50%"],18,C.red,900,22,"start",true)}${pill(400,745,240,"80% = shorter",C.maroon,C.redBg)}${pill(650,745,240,"50% = longer",C.red,C.redBg)}${card(1320,435,185,225,C.brown,C.amberBg)}${txt(1412,490,["SAME"],17,C.brown,900,21,"middle",true)}${txt(1412,532,["model"],23,C.ink,850,28,"middle")}${txt(1412,580,["DIFFERENT"],17,C.brown,900,21,"middle",true)}${txt(1412,622,["claim"],23,C.ink,850,28,"middle")}`); }
function renderTrend(s: Slide) { const pts=[[180,690],[320,660],[455,625],[590,590],[730,555],[870,510],[1010,465]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="11" fill="${C.cobalt}"/>`).join(""); return shell(`${header(s)}${card(90,400,1040,350,C.line,C.paper)}<path d="M150 710 L1080 420" fill="none" stroke="${C.cobalt}" stroke-width="6"/>${pts}${txt(590,690,["historical fit  |  approximately 7-month doubling"],18,C.cobalt,850,22,"middle",true)}${card(1160,400,350,350,C.red,C.redBg)}${txt(1335,480,["UNCERTAINTY"],19,C.red,900,23,"middle",true)}${txt(1335,535,["future systems"],20,C.ink,750,25,"middle")}${txt(1335,575,["task distribution"],20,C.ink,750,25,"middle")}${txt(1335,615,["deployment context"],20,C.ink,750,25,"middle")}${txt(1335,690,["NO FORECAST"],18,C.red,900,22,"middle",true)}${caveat(360,785,880,"A historical benchmark trend is evidence about the studied period, not a deployment guarantee.")}`); }
function renderFailures(s: Slide) { const nodes=[[120,"PLAN",C.cobalt],[410,"ACT",C.teal],[700,"OBSERVE",C.brown],[990,"RECOVER",C.green],[1280,"FINISH",C.maroon]] as const; const branches=[[530,"wrong tool"],[610,"loop"],[690,"abandon"]] as const; return shell(`${header(s)}${nodes.map(([x,label,color],i)=>`${card(x,455,220,125,color,C.paper)}${txt(x+110,510,[label],20,color,900,24,"middle",true)}${txt(x+110,548,[`trace ${i+1}`],15,C.muted,700,19,"middle",true)}${i<4?arrow(x+220,518,x+275,518,C.teal):""}`).join("")}${branches.map(([y,label],i)=>`${arrow(805,580,900,y,C.red,3)}${pill(900,y-28,220,label,C.red,C.redBg)}`).join("")}${card(370,755,860,60,C.teal,C.tealBg)}${txt(800,793,["PRESERVE THE TRACE  ->  LOCALIZE THE FAILURE"],18,C.teal,900,22,"middle",true)}`); }
function renderGDPval(s: Slide) { const xs=[90,400,760,1120]; const labs=[["WORK BRIEF","bounded context"],["MODEL OUTPUT","deliverable A"],["REFERENCE","deliverable B"],["DOMAIN EXPERT","pairwise judgment"]] as const; const colors=[C.cobalt,C.teal,C.brown,C.maroon]; return shell(`${header(s)}${labs.map(([a,b],i)=>`${card(xs[i],455,300,185,colors[i],C.paper)}${txt(xs[i]+150,512,[a],19,colors[i],900,23,"middle",true)}${txt(xs[i]+150,565,[b],20,C.ink,760,25,"middle")}${i<3?arrow(xs[i]+300,548,xs[i]+340,548,C.teal):""}`).join("")}${caveat(350,730,900,"GDPval evaluates sampled deliverables under supplied context, not entire jobs or deployment readiness.")}`); }
function renderSampling(s: Slide) { const stages=[[90,420,"9","SECTORS",C.cobalt],[425,465,"44","OCCUPATIONS",C.brown],[780,510,"1,320","TASKS",C.teal],[1160,555,"220","OPEN SET",C.maroon]] as const; return shell(`${header(s)}${stages.map(([x,y,n,l,color],i)=>`${card(x,y,300,175,color,C.paper)}${txt(x+150,y+72,[n],44,color,930,52,"middle",true)}${txt(x+150,y+125,[l],17,C.ink,850,21,"middle",true)}${i<3?arrow(x+300,y+88,Number(stages[i+1][0])-25,Number(stages[i+1][1])+88,C.teal):""}`).join("")}${pill(1040,735,390,"professionals avg. 14 years",C.brown,C.amberBg)}${caveat(200,760,750,"Broad sampling remains bounded sampling; tasks do not stand in for every activity in an occupation.")}`); }
function renderHeterogeneity(s: Slide) { const hs=[80,210,135,280,55,245,165,305,110,230]; const bars=hs.map((h,i)=>`<rect x="660" y="${720-h}" width="55" height="${h}" rx="5" fill="${i%3===0?C.maroon:i%2?C.teal:C.brown}" transform="translate(${i*72} 0)"/>`).join(""); return shell(`${header(s)}${card(90,425,430,300,C.cobalt,C.blueBg)}${txt(305,495,["AGGREGATE"],18,C.cobalt,900,22,"middle",true)}<rect x="175" y="560" width="260" height="72" rx="6" fill="${C.cobalt}"/>${txt(305,607,["near parity"],24,"#fff",900,29,"middle",true)}${card(590,425,920,300,C.line,C.paper)}${txt(640,470,["TASK-LEVEL OUTCOMES"],18,C.muted,900,22,"start",true)}${bars}${txt(1080,755,["same average  !=  same capability everywhere"],18,C.red,850,22,"middle",true)}${caveat(365,785,870,"Aggregate preference does not establish task-by-task equivalence or occupational replacement.")}`); }
function renderTriangle(s: Slide) { return shell(`${header(s)}<path d="M800 405 L460 720 L1140 720 Z" fill="${C.blueBg}" stroke="${C.cobalt}" stroke-width="4"/>${card(670,390,260,100,C.cobalt,C.paper)}${txt(800,432,["SYNTHESIS"],18,C.cobalt,900,22,"middle",true)}${txt(800,466,["coherence"],17,C.ink,700,21,"middle")}${card(300,680,260,100,C.teal,C.paper)}${txt(430,722,["RETRIEVAL"],18,C.teal,900,22,"middle",true)}${txt(430,756,["coverage"],17,C.ink,700,21,"middle")}${card(1040,680,260,100,C.maroon,C.paper)}${txt(1170,722,["VERIFIABILITY"],18,C.maroon,900,22,"middle",true)}${txt(1170,756,["citation support"],17,C.ink,700,21,"middle")}${txt(800,610,["A fluent report can"],20,C.ink,750,25,"middle")}${txt(800,642,["fail any one dimension."],23,C.red,900,28,"middle")}`); }
function renderVersions(s: Slide) { return shell(`${header(s)}${card(90,415,550,280,C.brown,C.amberBg)}${txt(365,465,["LECTURE SNAPSHOT"],18,C.brown,900,22,"middle",true)}${txt(365,520,["AUTUMN 2025"],17,C.ink,800,21,"middle",true)}${txt(365,605,["19%"],60,C.brown,930,70,"middle",true)}${txt(365,655,["no system exceeded lecture aggregate"],17,C.ink,680,21,"middle")}${card(960,415,550,280,C.teal,C.tealBg)}${txt(1235,465,["ARXIV V2 SNAPSHOT"],18,C.teal,900,22,"middle",true)}${txt(1235,520,["2026-02-09"],17,C.ink,800,21,"middle",true)}${txt(1235,605,["31%"],60,C.teal,930,70,"middle",true)}${txt(1235,655,["geometric mean in current abstract"],17,C.ink,680,21,"middle")}${card(675,400,250,325,C.red,C.redBg)}${txt(800,465,["DO NOT"],22,C.red,930,27,"middle",true)}${txt(800,505,["SUBTRACT"],22,C.red,930,27,"middle",true)}${txt(800,575,["different revisions"],16,C.ink,760,20,"middle")}${txt(800,610,["possibly different"],16,C.ink,760,20,"middle")}${txt(800,635,["aggregation / systems"],16,C.ink,760,20,"middle")}${txt(800,690,["NOT A TREND"],18,C.red,930,22,"middle",true)}${caveat(290,770,1020,"The two values are separately sourced snapshots and are not directly comparable.")}`); }
function renderPortfolio(s: Slide) { const cols=[[90,"CLAIM",C.cobalt],[330,"DISTRIBUTION",C.teal],[600,"THRESHOLD",C.brown],[850,"CONTEXT",C.teal],[1080,"VERSION",C.maroon],[1290,"BLIND SPOT",C.red]] as const; const rows=["long tasks","valuable work","research synthesis"]; return shell(`${header(s)}${cols.map(([x,l,color])=>`${card(x,400,200,62,color,color===C.red?C.redBg:C.paper)}${txt(x+100,439,[l],14,color,900,18,"middle",true)}`).join("")}${rows.map((r,j)=>cols.map(([x,_l,color],i)=>`${card(x,480+j*92,200,72,i===5?C.red:C.line,i===5?C.redBg:C.paper)}${txt(x+100,523+j*92,[i===0?r:["task set","success target","supplied info","paper / date","what is missing"][i-1]],15,i===5?C.red:C.ink,760,19,"middle")}`).join("")).join("")}${card(450,785,700,54,C.cobalt,C.blueBg)}${txt(800,819,["CLAIM SCOPE <= EVIDENCE SCOPE"],18,C.cobalt,900,22,"middle",true)}`); }

const renderers: Record<string,(s:Slide)=>string> = { cover:renderCover, axes:renderAxes, horizon:renderHorizon, thresholds:renderThresholds, trend:renderTrend, failures:renderFailures, gdpval:renderGDPval, sampling:renderSampling, heterogeneity:renderHeterogeneity, triangle:renderTriangle, versions:renderVersions, portfolio:renderPortfolio };

function prompt(slide: Slide, index: number) { return `# Slide ${index + 1}: ${slide.title.join(" ")}\n\n## Production method\nRendered locally as an original 1600x900 SVG for exact text fidelity, then converted to PNG. Do not reproduce Stanford frames, figures, or logos.\n\n## Style\nAged-cream academic technical briefing, faint engineering grid, crisp vector diagrams, near-black type, cobalt generation, teal verification, warm-brown budget, maroon constraints, 8px card corners, no gradients.\n\n## On-slide content\n- Stage: ${slide.stage}\n- Headline: ${slide.title.join(" ")}\n- Subtitle: ${slide.subtitle}\n- Supporting labels: ${slide.labels.join("; ")}\n- Evidence: CS329A Part 8, ${slide.evidence}\n\n## Visual direction\n${slide.visual}\n\n## Teaching objective\n${slide.objective}\n\n## Speaker notes\n${slide.notes}\n`; }

function contactSheet() { const tw=480,th=270,gap=26,margin=34,labelH=58,cols=3,rows=Math.ceil(slides.length/cols),cw=margin*2+cols*tw+(cols-1)*gap,ch=margin*2+rows*(th+labelH)+(rows-1)*gap; const images=slides.map((s,i)=>{const x=margin+(i%cols)*(tw+gap),y=margin+Math.floor(i/cols)*(th+labelH+gap),data=readFileSync(join(DIR,`${s.file}.png`)).toString("base64"),lines=wrap(`${String(i+1).padStart(2,"0")}  ${s.title.join(" ")}`,52).slice(0,2);return `<image href="data:image/png;base64,${data}" x="${x}" y="${y}" width="${tw}" height="${th}"/>${txt(x,y+th+23,lines,15,C.ink,750,19)}`;}).join(""); return `<svg xmlns="http://www.w3.org/2000/svg" width="${cw}" height="${ch}" viewBox="0 0 ${cw} ${ch}"><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}</style><rect width="${cw}" height="${ch}" fill="#E8E2D7"/>${images}</svg>`; }

ensure(SVG_DIR); ensure(PROMPT_DIR);
slides.forEach((slide,i)=>{ const svg=renderers[slide.kind](slide); const svgPath=join(SVG_DIR,`${slide.file}.svg`); const pngPath=join(DIR,`${slide.file}.png`); writeFileSync(svgPath,svg); writeFileSync(join(PROMPT_DIR,`${slide.file}.md`),prompt(slide,i)); const result=Bun.spawnSync(["sips","-s","format","png",svgPath,"--out",pngPath],{stdout:"pipe",stderr:"pipe"}); if(result.exitCode!==0) throw new Error(`sips failed for ${slide.file}: ${result.stderr.toString()}`); });
const sheetSvg=join(DIR,"contact-sheet.svg"); writeFileSync(sheetSvg,contactSheet()); const sheet=Bun.spawnSync(["sips","-s","format","png",sheetSvg,"--out",join(DIR,"contact-sheet.png")],{stdout:"pipe",stderr:"pipe"}); if(sheet.exitCode!==0) throw new Error(`sips failed for contact sheet: ${sheet.stderr.toString()}`);
console.log(`Rendered ${slides.length} slides, SVGs, prompts, and contact sheet in ${DIR}`);
