import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = import.meta.dir;
const SVG_DIR = join(DIR, "svgs");
const PROMPT_DIR = join(DIR, "prompts");
const W = 1600, H = 900;
const C = { bg:"#F5F0E6",paper:"#FFFCF4",ink:"#171717",muted:"#5E6670",line:"#D8D0C0",teal:"#2F7373",maroon:"#722F37",brown:"#8B7355",cobalt:"#2563EB",red:"#B42318",green:"#16803C",blueBg:"#F3F7FF",tealBg:"#F2FBF8",redBg:"#FFF5F3",amberBg:"#FFF9E8" };

type Slide = { file:string; stage:string; title:string[]; subtitle:string; labels:string[]; evidence:string; objective:string; notes:string; visual:string; kind:string };
const slides: Slide[] = [
 {file:"01-slide-self-improvement-stack",stage:"coupled system",title:["The Self-Improvement","Stack"],subtitle:"Diversity, verification, curriculum, adaptation, and infrastructure constrain one another.",labels:["Diversity","Verification","Curriculum","Adaptation","Infrastructure"],evidence:"00:00-06:51 + 65:23-67:42",objective:"Locate five bottlenecks in one loop.",notes:"Self-improvement is not one algorithm. Progress at one layer can reveal the next bottleneck. The integrated stack is teaching synthesis.",visual:"Five monitored layers around a bounded improvement loop.",kind:"stack"},
 {file:"02-slide-diversity-collapse",stage:"data flywheel",title:["Why One Model","Collapses Diversity"],subtitle:"Repeated self-training can narrow measured reasoning in the evaluated settings.",labels:["Round 0","Round 1","Round 2","Plateau"],evidence:"06:51-09:55 + Multiagent FT v2",objective:"Explain homogenization without universalizing it.",notes:"The paper reports a conditional result in evaluated reasoning settings. Similar surface forms are not the only issue; correlated assumptions can persist.",visual:"Many initial paths narrow into one repeated pattern over rounds.",kind:"collapse"},
 {file:"03-slide-specialized-roles",stage:"multiagent training",title:["Specialize Generators","and Critics"],subtitle:"Independent role updates create a society of solution and critique strategies.",labels:["Generate","Critique","Summarize","Vote"],evidence:"09:55-12:37 + Multiagent FT v2",objective:"Show role specialization and aggregation.",notes:"Agents here are model roles in a training workflow. Debate and voting do not guarantee truth when errors remain correlated.",visual:"Generator and critic roles exchange evidence before aggregation.",kind:"roles"},
 {file:"04-slide-diversity-metrics",stage:"proxy discipline",title:["Measure Diversity,","Not Just Accuracy"],subtitle:"Useful variation supports later learning, but diversity metrics remain proxies.",labels:["Accuracy","Likelihood","Embedding","Coverage"],evidence:"12:37-14:47 + Multiagent FT v2",objective:"Keep performance and diversity measurements separate.",notes:"Likelihood and embedding dissimilarity can reveal homogenization but cannot prove conceptual completeness. More variation may also mean more low-quality output.",visual:"Accuracy rises while two proxy-diversity curves separate.",kind:"metrics"},
 {file:"05-slide-invalid-proof",stage:"process verification",title:["Correct Answer,","Invalid Proof"],subtitle:"Outcome correctness cannot certify every transition in the reasoning path.",labels:["Premise","Valid step","Broken step","Correct endpoint"],evidence:"14:47-18:03 + DeepSeekMath-V2 v1",objective:"Separate outcome from process verification.",notes:"Proof-style tasks expose the gap clearly. A correct endpoint can be reached through an unjustified step.",visual:"A green endpoint follows a red broken intermediate proof step.",kind:"proof"},
 {file:"06-slide-meta-verification",stage:"recursive trust",title:["Verifier and","Meta-Verifier"],subtitle:"Check the proof, then check the feedback that judged the proof.",labels:["Generator","Verifier","Meta-verifier","Hard examples"],evidence:"18:03-22:35 + DeepSeekMath-V2 v1",objective:"Teach the verifier hierarchy and trust boundary.",notes:"Meta-verification improves feedback quality but does not create certainty. The evidence is mathematical and benchmark-specific.",visual:"Generator, verifier, and meta-verifier form an iterative cycle.",kind:"verify"},
 {file:"07-slide-proposer-solver",stage:"self-play tasks",title:["Let the Model","Propose Tasks"],subtitle:"Absolute Zero joins proposer and solver without an external task dataset.",labels:["Pretrained model","Propose","Solve","Execute"],evidence:"22:35-25:45 + Absolute Zero v3",objective:"Explain proposer-solver self-play and zero-data boundary.",notes:"Zero data means no external task dataset in this loop. The model is pretrained and program execution supplies structure.",visual:"One pretrained model branches into proposer and solver roles around an executor.",kind:"proposer"},
 {file:"08-slide-learnable-curriculum",stage:"curriculum frontier",title:["Build a Learnable","Curriculum"],subtitle:"Valid, intermediate-difficulty tasks feed an evolving buffer.",labels:["Deduction","Abduction","Induction","Buffer"],evidence:"25:45-33:07 + Absolute Zero v3",objective:"Explain learnability reward and curriculum dynamics.",notes:"Trivial tasks add little signal; impossible tasks yield no progress. Solver bias and buffer policy can narrow coverage.",visual:"A learnability peak lies between trivial and impossible tasks.",kind:"curriculum"},
 {file:"09-slide-verification-boundary",stage:"transfer boundary",title:["Verification Is","the Boundary"],subtitle:"Feedback becomes slower, costlier, and more contested beyond executable domains.",labels:["Unit test","Proof","Simulation","Experiment","Judgment"],evidence:"33:07-39:59 / discussion",objective:"Map transfer limits of self-generated curricula.",notes:"Learned rewards may extend reach but introduce misspecification and reward hacking. This is an open direction.",visual:"Verifiability spectrum from cheap objective checks to contested judgment.",kind:"spectrum"},
 {file:"10-slide-intelligence-per-watt",stage:"efficiency metric",title:["Intelligence","per Watt"],subtitle:"Average task accuracy divided by average power, under a bounded workload and system boundary.",labels:["20+ models","8 accelerators","1M queries","v5"],evidence:"39:59-51:53 + IPW v5",objective:"Define IPW and attach every number to study scope.",notes:"Current v5 reports 88.7 percent best-of-local routing coverage; a separate longitudinal win/tie-rate statistic reaches 71.3 percent in 2025; IPW improved 5.3x historically. Local accelerators have at least 1.4x lower IPW than cloud accelerators for identical models.",visual:"Accuracy-over-power fraction beside versioned scope and result cards.",kind:"ipw"},
 {file:"11-slide-local-cloud-router",stage:"systems routing",title:["Local, Cloud,","or Hybrid?"],subtitle:"Route by capability, privacy, latency, energy, and cost; abstain when requirements fail.",labels:["Local","Cloud","Hybrid","Abstain"],evidence:"48:51-57:00 + IPW v5 / synthesis",objective:"Frame deployment as a multi-objective router.",notes:"No path wins universally. Local execution can help privacy or latency, but it does not guarantee privacy or lower total energy.",visual:"A query router scores objectives before choosing local, cloud, or abstain.",kind:"router"},
 {file:"12-slide-research-agenda",stage:"research audit",title:["The Research","Agenda"],subtitle:"Different experience; trustworthy feedback; learnable tasks; durable adaptation; efficient delivery.",labels:["Difference","Verify","Learn","Persist","Deliver"],evidence:"51:53-67:42 / synthesis",objective:"Apply a five-question research audit.",notes:"The four papers do not evaluate an integrated stack. Use the questions to identify the limiting layer and a falsification test.",visual:"Five audit questions surround a bounded improvement loop.",kind:"agenda"}
];

function ensure(p:string){if(!existsSync(p))mkdirSync(p,{recursive:true});}
function esc(s:string){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
function measure(s:string){return [...s].reduce((n,ch)=>n+(/[^\x00-\x7F]/.test(ch)?1.7:1),0);}
function wrap(s:string,max:number){const out:string[]=[];let line="";for(const word of s.split(/\s+/)){const next=line?`${line} ${word}`:word;if(measure(next)>max&&line){out.push(line);line=word;}else line=next;}if(line)out.push(line);return out;}
function txt(x:number,y:number,lines:string[],size:number,color=C.ink,weight=700,lh=Math.round(size*1.18),anchor:"start"|"middle"="start",mono=false){return lines.map((line,i)=>`<text class="${mono?"mono":"ui"}" x="${x}" y="${y+i*lh}" fill="${color}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}">${esc(line)}</text>`).join("");}
function card(x:number,y:number,w:number,h:number,stroke=C.line,fill=C.paper,rx=8){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="2"/>`;}
function arrow(x1:number,y1:number,x2:number,y2:number,color=C.teal,width=4,dash=""){return `<path d="M${x1} ${y1} L${x2} ${y2}" fill="none" stroke="${color}" stroke-width="${width}" ${dash?`stroke-dasharray="${dash}"`:""} marker-end="url(#arrow)"/>`;}
function pill(x:number,y:number,w:number,label:string,color=C.teal,fill=C.paper){return `${card(x,y,w,56,color,fill)}${txt(x+w/2,y+35,[label],17,color,850,21,"middle",true)}`;}
function shell(inner:string){return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><pattern id="grid" width="46" height="46" patternUnits="userSpaceOnUse"><path d="M46 0 L0 0 0 46" fill="none" stroke="${C.line}" opacity=".38"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="context-stroke"/></marker></defs><style>.ui{font-family:-apple-system,BlinkMacSystemFont,"Inter","Segoe UI",Arial,sans-serif;letter-spacing:0}.mono{font-family:"SFMono-Regular","SF Mono",Consolas,monospace;letter-spacing:0}</style><rect width="1600" height="900" fill="${C.bg}"/><rect width="1600" height="900" fill="url(#grid)"/><rect x="42" y="42" width="1516" height="816" rx="8" fill="${C.paper}" opacity=".92"/>${inner}</svg>`;}
function badge(s:Slide){const w=Math.max(220,measure(s.stage)*12+54);return `${card(84,68,w,43,C.teal,C.tealBg)}${txt(108,97,[s.stage.toUpperCase()],17,C.teal,900,21,"start",true)}`;}
function evidence(s:Slide){const label=`PART 9  ${s.evidence}`,w=Math.min(690,Math.max(350,measure(label)*9.4+42));return `${card(1516-w,68,w,43,C.line,C.paper)}${txt(1516-w/2,97,[label],15,C.muted,760,19,"middle",true)}`;}
function header(s:Slide){return `${badge(s)}${evidence(s)}${txt(86,188,s.title,50,C.ink,920,57)}${txt(90,188+s.title.length*57+18,wrap(s.subtitle,91),23,C.muted,560,29)}`;}
function boundary(x:number,y:number,w:number,label:string){const lines=wrap(label,Math.floor(w/12));return `${card(x,y,w,40+lines.length*25,C.red,C.redBg)}${txt(x+18,y+27,["BOUNDARY"],14,C.red,900,18,"start",true)}${txt(x+18,y+54,lines,18,C.ink,630,25)}`;}

function visual(s:Slide){const h=header(s);if(s.kind==="stack"){const items=[[160,"DIVERSITY",C.cobalt],[430,"VERIFY",C.teal],[700,"CURRICULUM",C.brown],[970,"ADAPT",C.green],[1240,"INFRA",C.maroon]] as const;return shell(`${badge(s)}${evidence(s)}${txt(90,245,s.title,64,C.ink,930,74)}${txt(94,455,wrap(s.subtitle,38),25,C.muted,560,32)}${items.map(([x,l,c],i)=>`${card(x,600-i%2*35,210,110,c,C.paper)}${txt(x+105,655-i%2*35,[l],17,c,900,21,"middle",true)}${i<4?arrow(x+210,655-i%2*35,x+255,620+(i+1)%2*35,C.teal,3):""}`).join("")}${card(650,760,300,54,C.red,C.redBg)}${txt(800,794,["MONITOR  ->  STOP"],17,C.red,900,21,"middle",true)}`);}
if(s.kind==="collapse"){const ys=[420,485,550,615,680];return shell(`${h}${ys.map((y,i)=>`${pill(100,y,180,`path ${i+1}`,C.cobalt,C.blueBg)}${arrow(280,y+28,620,525+i*8,C.cobalt,3)}`).join("")}${card(620,460,250,190,C.brown,C.amberBg)}${txt(745,515,["SELF-TRAIN"],19,C.brown,900,23,"middle",true)}${txt(745,560,["same source"],18,C.ink,720,22,"middle")}${txt(745,600,["many rounds"],18,C.ink,720,22,"middle")}${[450,520,590].map(y=>`${arrow(870,555,1100,y,C.maroon,3)}${pill(1100,y-28,300,"repeated reasoning",C.maroon,C.redBg)}`).join("")}${boundary(420,750,760,"Observed in the paper's evaluated settings; not every single-model loop must collapse.")}`);}
if(s.kind==="roles"){const roles=[[120,430,"GENERATOR A",C.cobalt],[120,600,"GENERATOR B",C.cobalt],[520,430,"CRITIC A",C.teal],[520,600,"CRITIC B",C.teal]] as const;return shell(`${h}${roles.map(([x,y,l,c])=>`${card(x,y,260,120,c,C.paper)}${txt(x+130,y+68,[l],18,c,900,22,"middle",true)}`).join("")}${arrow(380,490,520,490,C.teal)}${arrow(380,660,520,660,C.teal)}${arrow(650,550,850,550,C.brown)}${card(850,465,260,170,C.brown,C.amberBg)}${txt(980,520,["DEBATE"],19,C.brown,900,23,"middle",true)}${txt(980,560,["summarize"],18,C.ink,720,22,"middle")}${txt(980,595,["vote"],18,C.ink,720,22,"middle")}${arrow(1110,550,1260,550,C.maroon)}${pill(1260,522,220,"training data",C.maroon,C.redBg)}${boundary(430,760,740,"Specialized roles can still share correlated blind spots.")}`);}
if(s.kind==="metrics"){const curves=`<path d="M160 700 C350 610 520 520 700 470" fill="none" stroke="${C.green}" stroke-width="7"/><path d="M820 490 C1010 500 1190 560 1450 640" fill="none" stroke="${C.cobalt}" stroke-width="7"/><path d="M820 540 C1020 535 1210 575 1450 610" fill="none" stroke="${C.teal}" stroke-width="7"/>`;return shell(`${h}${card(90,405,650,340,C.green,C.tealBg)}${txt(130,455,["ACCURACY"],18,C.green,900,22,"start",true)}${card(780,405,730,340,C.cobalt,C.blueBg)}${txt(820,455,["DIVERSITY PROXIES"],18,C.cobalt,900,22,"start",true)}${curves}${txt(1130,685,["likelihood  /  embedding"],18,C.ink,760,22,"middle",true)}${boundary(370,765,860,"Proxy diversity is not semantic completeness, independence, or quality.")}`);}
if(s.kind==="proof"){const xs=[90,400,710,1020,1330],labs=["PREMISE","VALID STEP","BROKEN STEP","VALID STEP","CORRECT"],colors=[C.cobalt,C.teal,C.red,C.teal,C.green];return shell(`${h}${xs.map((x,i)=>`${card(x,470,230,150,colors[i],i===2?C.redBg:C.paper)}${txt(x+115,530,[labs[i]],18,colors[i],900,22,"middle",true)}${txt(x+115,575,[i===2?"unsupported":"accepted"],16,C.ink,700,20,"middle")}${i<4?arrow(x+230,545,x+285,545,i===1?C.red:C.teal,4):""}`).join("")}${txt(800,700,["RIGHT ENDPOINT  !=  VALID REASONING"],27,C.red,900,32,"middle",true)}`);}
if(s.kind==="verify"){const nodes=[[280,555,"GENERATOR",C.cobalt],[690,430,"VERIFIER",C.teal],[1110,555,"META-VERIFIER",C.maroon]] as const;return shell(`${h}${nodes.map(([x,y,l,c])=>`${card(x-140,y-70,280,140,c,C.paper)}${txt(x,y-10,[l],19,c,900,23,"middle",true)}${txt(x,y+32,[l==="GENERATOR"?"proof":l==="VERIFIER"?"issue report":"check feedback"],17,C.ink,700,21,"middle")}`).join("")}${arrow(420,555,550,465,C.cobalt)}${arrow(830,465,970,535,C.teal)}<path d="M1110 625 C1000 760 440 760 280 625" fill="none" stroke="${C.maroon}" stroke-width="4" marker-end="url(#arrow)"/>${pill(690,680,250,"hard examples",C.brown,C.amberBg)}${boundary(420,770,760,"A meta-verifier moves the trust boundary; it does not create certainty.")}`);}
if(s.kind==="proposer"){return shell(`${h}${card(90,465,320,190,C.cobalt,C.blueBg)}${txt(250,525,["PRETRAINED"],18,C.cobalt,900,22,"middle",true)}${txt(250,565,["MODEL"],27,C.ink,900,32,"middle",true)}${arrow(410,525,650,440,C.cobalt)}${arrow(410,595,650,650,C.teal)}${card(650,390,300,140,C.cobalt,C.paper)}${txt(800,450,["PROPOSE TASK"],20,C.cobalt,900,24,"middle",true)}${card(650,590,300,140,C.teal,C.paper)}${txt(800,650,["SOLVE TASK"],20,C.teal,900,24,"middle",true)}${arrow(950,460,1160,535,C.brown)}${arrow(950,660,1160,585,C.brown)}${card(1160,480,330,180,C.brown,C.amberBg)}${txt(1325,540,["CODE EXECUTOR"],20,C.brown,900,24,"middle",true)}${txt(1325,585,["validity + answer"],18,C.ink,720,22,"middle")}${boundary(400,760,800,"Zero external task data in this loop does not mean zero pretraining or structure.")}`);}
if(s.kind==="curriculum"){const curve=`<path d="M130 695 C380 690 500 455 800 430 C1100 455 1220 690 1480 695" fill="none" stroke="${C.cobalt}" stroke-width="7"/>`;return shell(`${h}${card(90,405,1420,340,C.line,C.paper)}${curve}${txt(240,680,["TRIVIAL"],18,C.brown,900,22,"middle",true)}${txt(800,455,["LEARNABLE"],20,C.green,900,24,"middle",true)}${txt(1360,680,["IMPOSSIBLE"],18,C.red,900,22,"middle",true)}${pill(430,620,210,"deduction",C.cobalt,C.blueBg)}${pill(695,560,210,"abduction",C.teal,C.tealBg)}${pill(960,620,210,"induction",C.maroon,C.redBg)}${card(610,760,380,54,C.green,C.tealBg)}${txt(800,794,["VALIDATE  ->  BUFFER  ->  PROPOSE"],17,C.green,900,21,"middle",true)}`);}
if(s.kind==="spectrum"){const items=[[80,"UNIT TEST",C.green],[370,"PROOF",C.teal],[660,"SIMULATION",C.cobalt],[950,"EXPERIMENT",C.brown],[1240,"JUDGMENT",C.maroon]] as const;return shell(`${h}${items.map(([x,l,c],i)=>`${card(x,470,250,150,c,C.paper)}${txt(x+125,530,[l],18,c,900,22,"middle",true)}${txt(x+125,575,[i<2?"cheap / objective":i===2?"model-bound":i===3?"slow / noisy":"contested"],16,C.ink,700,20,"middle")}${i<4?arrow(x+250,545,x+290,545,C.teal):""}`).join("")}<path d="M140 700 L1460 700" stroke="${C.red}" stroke-width="6"/><path d="M1460 700 l-18 -10 v20z" fill="${C.red}"/>${txt(800,740,["COST + AMBIGUITY RISE"],18,C.red,900,22,"middle",true)}${boundary(380,770,840,"Learned reward extends reach while increasing misspecification risk.")}`);}
if(s.kind==="ipw"){return shell(`${h}${card(90,430,470,270,C.cobalt,C.blueBg)}${txt(325,490,["INTELLIGENCE / WATT"],19,C.cobalt,900,23,"middle",true)}${txt(325,565,["average task accuracy"],22,C.ink,850,27,"middle")}${txt(325,605,["-----------------------"],18,C.cobalt,800,22,"middle",true)}${txt(325,650,["average power"],22,C.ink,850,27,"middle")}${card(610,430,390,270,C.teal,C.tealBg)}${txt(805,480,["CURRENT V5 SCOPE"],18,C.teal,900,22,"middle",true)}${txt(805,535,["20+ local models"],20,C.ink,760,25,"middle")}${txt(805,575,["8 accelerators"],20,C.ink,760,25,"middle")}${txt(805,615,["1M single-turn queries"],20,C.ink,760,25,"middle")}${card(1050,430,460,270,C.brown,C.amberBg)}${txt(1280,480,["REPORTED"],18,C.brown,900,22,"middle",true)}${txt(1280,540,["88.7% best-of-local"],22,C.ink,850,27,"middle")}${txt(1280,580,["5.3x historical IPW"],22,C.ink,850,27,"middle")}${txt(1280,620,["local >=1.4x lower IPW"],19,C.red,850,23,"middle")}${boundary(330,750,940,"Versioned study results; not all requests, not a forecast, and not a universal hardware ranking.")}`);}
if(s.kind==="router"){const rows=[[420,"CAPABILITY",C.cobalt],[500,"PRIVACY",C.teal],[580,"LATENCY",C.brown],[660,"ENERGY + COST",C.maroon]] as const;return shell(`${h}${card(90,480,250,160,C.cobalt,C.blueBg)}${txt(215,540,["QUERY"],20,C.cobalt,900,24,"middle",true)}${txt(215,582,["requirements"],18,C.ink,720,22,"middle")}${rows.map(([y,l,c])=>`${arrow(340,560,600,y+28,c,3)}${pill(600,y,260,l,c,C.paper)}`).join("")}${arrow(860,520,1060,445,C.green)}${arrow(860,565,1060,565,C.teal)}${arrow(860,610,1060,685,C.red)}${pill(1060,417,300,"LOCAL",C.green,C.tealBg)}${pill(1060,537,300,"CLOUD",C.teal,C.blueBg)}${pill(1060,657,300,"ABSTAIN",C.red,C.redBg)}${boundary(500,770,720,"Routing is multi-objective; no path wins every workload.")}`);}
const qs=[[250,485,"01","DIFFERENCE",C.cobalt],[525,630,"02","VERIFY",C.teal],[800,485,"03","LEARN",C.brown],[1075,630,"04","PERSIST",C.green],[1350,485,"05","DELIVER",C.maroon]] as const;return shell(`${h}${qs.map(([x,y,n,l,c])=>`${card(x-115,y-75,230,150,c,C.paper)}${txt(x,y-28,[n],15,c,900,19,"middle",true)}${txt(x,y+14,[l],17,c,900,21,"middle",true)}${txt(x,y+48,[l==="DIFFERENCE"?"new experience?":l==="VERIFY"?"trusted signal?":l==="LEARN"?"useful task?":l==="PERSIST"?"memory / weights?":"latency / energy?"],14,C.ink,680,18,"middle")}`).join("")}${arrow(365,485,410,585,C.teal)}${arrow(640,585,685,485,C.teal)}${arrow(915,485,960,585,C.teal)}${arrow(1190,585,1235,485,C.teal)}${card(500,760,600,56,C.red,C.redBg)}${txt(800,795,["IDENTIFY LIMIT  ->  DESIGN FALSIFICATION"],17,C.red,900,21,"middle",true)}`);}

function prompt(s:Slide,i:number){return `# Slide ${i+1}: ${s.title.join(" ")}\n\n## Production method\nOriginal 1600x900 local SVG rendered to PNG for exact text fidelity. No copied Stanford frames, figures, logos, or paper graphics.\n\n## Style\nAged cream academic briefing, engineering grid, near-black type, cobalt proposals, teal verification, warm-brown compute, maroon constraints, red risks, no gradients.\n\n## On-slide content\n- Stage: ${s.stage}\n- Headline: ${s.title.join(" ")}\n- Subtitle: ${s.subtitle}\n- Labels: ${s.labels.join("; ")}\n- Evidence: CS329A Part 9, ${s.evidence}\n\n## Visual direction\n${s.visual}\n\n## Teaching objective\n${s.objective}\n\n## Speaker notes\n${s.notes}\n`;}
function contact(){const tw=480,th=270,gap=26,margin=34,labelH=58,cols=3,rows=Math.ceil(slides.length/cols),cw=margin*2+cols*tw+(cols-1)*gap,ch=margin*2+rows*(th+labelH)+(rows-1)*gap;const imgs=slides.map((s,i)=>{const x=margin+(i%cols)*(tw+gap),y=margin+Math.floor(i/cols)*(th+labelH+gap),data=readFileSync(join(DIR,`${s.file}.png`)).toString("base64"),lines=wrap(`${String(i+1).padStart(2,"0")}  ${s.title.join(" ")}`,52).slice(0,2);return `<image href="data:image/png;base64,${data}" x="${x}" y="${y}" width="${tw}" height="${th}"/>${txt(x,y+th+23,lines,15,C.ink,750,19)}`;}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" width="${cw}" height="${ch}" viewBox="0 0 ${cw} ${ch}"><rect width="${cw}" height="${ch}" fill="#E8E2D7"/>${imgs}</svg>`;}

ensure(SVG_DIR);ensure(PROMPT_DIR);
slides.forEach((s,i)=>{const svg=visual(s),svgPath=join(SVG_DIR,`${s.file}.svg`),pngPath=join(DIR,`${s.file}.png`);writeFileSync(svgPath,svg);writeFileSync(join(PROMPT_DIR,`${s.file}.md`),prompt(s,i));const r=Bun.spawnSync(["sips","-s","format","png",svgPath,"--out",pngPath],{stdout:"pipe",stderr:"pipe"});if(r.exitCode!==0)throw new Error(r.stderr.toString());});
writeFileSync(join(DIR,"contact-sheet.svg"),contact());const sheet=Bun.spawnSync(["sips","-s","format","png",join(DIR,"contact-sheet.svg"),"--out",join(DIR,"contact-sheet.png")],{stdout:"pipe",stderr:"pipe"});if(sheet.exitCode!==0)throw new Error(sheet.stderr.toString());
console.log(`Rendered ${slides.length} slides, SVGs, prompts, and contact sheet in ${DIR}`);
